export const lifecycle = [
  { step: "01", label: "Identify", detail: "Resolve the person, asset, device, venue, role, or system." },
  { step: "02", label: "Authorize", detail: "Apply permission, scope, mode, and human-approval boundaries." },
  { step: "03", label: "Execute", detail: "Run the approved creative, operational, financial, or integration workflow." },
  { step: "04", label: "Record", detail: "Connect agreements, actions, provider references, and outcomes." },
  { step: "05", label: "Reconcile", detail: "Compare expected and actual activity, including liabilities and exceptions." },
  { step: "06", label: "Verify", detail: "Preserve enough context for an authorized reviewer to reconstruct the event." },
];

export const proofStrip = [
  { label: "Origin", value: "Concealed-image carriers", note: "May 2025 technology record", href: "#origin", color: "#8C4BFF" },
  { label: "Creative systems", value: "91 Secure QR payloads", note: "Image Lab + interactive media", href: "#domain-media", color: "#00E4FF" },
  { label: "Operational proof", value: "NUPS", note: "Hardware-tested venue workflows", href: "#nups-proof", color: "#34D399" },
  { label: "Intelligence", value: "GlyphBot + Auto-DJ", note: "Fable visuals and diagnostics", href: "#technical-systems", color: "#F5B942" },
  { label: "Value records", value: "GlyphBucks + ledgers", note: "Liability and reconciliation", href: "#financial-accountability", color: "#FBBF24" },
  { label: "Integration", value: "SDK · API · OHIP", note: "Provider and hardware rails", href: "#domain-integration", color: "#C084FC" },
];

export const originTimeline = [
  {
    year: "May 2025",
    title: "The carrier question",
    body: "A conversation about camouflage led to a practical question: could a familiar image carry machine-readable context without becoming a visible QR square?",
  },
  {
    year: "Working experiment",
    title: "LSB encode and decode",
    body: "Supported experiments altered selected least-significant pixel bits so permitted data could be encoded and later recovered while the image remained visually recognizable.",
  },
  {
    year: "Interactive media",
    title: "Hotspots and typed actions",
    body: "The image became an interface: normalized hotspot regions could carry links or text, remain usable across screen sizes, and retain shareable context.",
  },
  {
    year: "Structured carriers",
    title: "Secure QR Studio",
    body: "The carrier idea expanded into a working catalog of 91 payload definitions spanning links, identity, tickets, credentials, records, and operational references.",
  },
  {
    year: "Venue floor",
    title: "The same problem appeared in physical operations",
    body: "IDs, contracts, registers, shifts, payouts, and reports lived in separate places. Each tool kept a fragment while the full event was difficult to reconstruct.",
  },
  {
    year: "Operating proof",
    title: "NUPS connected the night",
    body: "Nexus Unified POS System connected venue context, identity, roles, agreements, transaction references, batches, reconciliation, and audit history.",
  },
  {
    year: "GlyphLock ecosystem",
    title: "One pattern across many systems",
    body: "Creative media, assisted intelligence, venue operations, stored value, APIs, hardware, and governance now resolve toward the same connected-record principle.",
  },
];

export const domains = [
  {
    id: "identity",
    number: "01",
    label: "Identity & Permission",
    short: "Identity",
    color: "#00E4FF",
    problem: "An action has little meaning until the system knows who or what is acting, where, under which role, and with what authority.",
    inputs: ["People and creator profiles", "Assets and devices", "Venue, role, and operating mode", "Credentials and contract references"],
    actions: ["ID scanning and age gating", "Profile matching and context resolution", "Role, venue, and mode scoping", "Authentication and access decisions"],
    records: ["Profile reference", "Verification result", "Permission decision", "Venue and mode context"],
    handoff: "Authorized context moves to contracts, operations, media, value, or an integration workflow.",
    maturity: "Implemented",
    statusNote: "Present across current workflows",
    modules: ["Front Door", "Guest profiles", "Role workspaces", "Contract identity"],
    links: [
      { label: "See the NUPS walkthrough", to: "/NUPSLanding#nups-walkthrough" },
      { label: "Read the NUPS case study", to: "/CaseStudyNUPS" },
      { label: "Trust and security", to: "/TrustSecurity" },
    ],
  },
  {
    id: "media",
    number: "02",
    label: "Media & Carriers",
    short: "Carriers",
    color: "#8C4BFF",
    problem: "Creative work needs a way to carry destinations, permissions, provenance, and machine-readable context without becoming disconnected from the asset.",
    inputs: ["Source images and creative work", "Permitted payloads and destinations", "Hotspot regions and typed actions", "Ownership and provenance context"],
    actions: ["Generate structured QR assets", "Encode and recover supported LSB payloads", "Map normalized interactive hotspots", "Hash, protect, share, and export assets"],
    records: ["QR asset and version", "Hotspot map and payload", "Image hash or evidence reference", "Scan and interaction events"],
    handoff: "The carrier delivers context to identity, verification, analytics, operations, or an external application.",
    maturity: "Implemented + research",
    statusNote: "QR and hotspots working; concealed carrier unreleased",
    modules: ["Secure QR Studio", "Image Lab", "Interactive Image Studio", "Protected evidence"],
    links: [
      { label: "Secure QR Studio", to: "/SecureQRStudio" },
      { label: "Image Lab", to: "/ImageLab" },
      { label: "Interactive Image Studio", to: "/InteractiveImageStudio" },
      { label: "QR SDK guidance", to: "/SDKDocs#qr" },
    ],
  },
  {
    id: "intelligence",
    number: "03",
    label: "Intelligence & Automation",
    short: "Intelligence",
    color: "#F5B942",
    problem: "Complex systems need assistance that can construct, inspect, orchestrate, and explain work without silently replacing human authority.",
    inputs: ["User instructions and knowledge", "Code, assets, operational state, and evidence", "Track libraries and crowd context", "Human constraints and approval"],
    actions: ["Plan, build, inspect, and audit", "Generate and resolve playlists", "Prepare Auto-DJ transitions", "Drive Fable visuals and diagnostics"],
    records: ["Assisted decision context", "Audit or change output", "Playlist and transition plan", "Playback telemetry"],
    handoff: "Approved assistance moves into a creative, operational, security, or venue-media workflow.",
    maturity: "Active development",
    statusNote: "Working surfaces with continuing hardening",
    modules: ["GlyphBot", "Site Builder", "Automated DJ", "Fable Engine", "Security audits"],
    links: [
      { label: "Meet GlyphBot", to: "/GlyphBot" },
      { label: "Open DJ Pro Mixer", to: "/GlyphBotMixer" },
      { label: "Open Fable Stage", to: "/FableStage" },
      { label: "Security operations", to: "/SecurityOperationsCenter" },
    ],
  },
  {
    id: "operations",
    number: "04",
    label: "Operations & Contracts",
    short: "Operations",
    color: "#34D399",
    problem: "A venue night is fragmented when identity, roles, agreements, registers, shifts, approvals, payouts, and reports cannot be reviewed as one event.",
    inputs: ["Guests, staff, contractors, and operators", "Venue rules and permissions", "Agreements and approvals", "Cash and external payment references"],
    actions: ["Check in and authorize", "Execute and sign agreements", "Run registers and role workspaces", "Close batches and review exceptions"],
    records: ["Profiles and shifts", "Contracts and signatures", "Transaction references", "Batches, reports, and audit events"],
    handoff: "Operational activity reaches accounting, reconciliation, security review, analytics, and authorized integrations.",
    maturity: "Operational proof",
    statusNote: "Hardware-tested in a real venue environment",
    modules: ["NUPS", "Front Door", "Contracts", "Registers", "Shifts", "Reports"],
    links: [
      { label: "Explore NUPS", to: "/NUPSLanding" },
      { label: "NUPS architecture", to: "/NUPSLanding#nups-architecture" },
      { label: "NUPS case study", to: "/CaseStudyNUPS" },
    ],
  },
  {
    id: "value",
    number: "05",
    label: "Value & Accounting",
    short: "Value",
    color: "#FBBF24",
    problem: "Money and stored value become dangerous when sales, liabilities, provider references, payouts, contracts, and exceptions are mixed together.",
    inputs: ["Cash and authorized card references", "GlyphBucks issuance and redemption", "Contracts and approvals", "Payouts, batches, and exceptions"],
    actions: ["Record cash and card activity", "Issue, verify, and redeem closed-loop value", "Maintain ledgers and liability roll-forward", "Reconcile expected and actual activity"],
    records: ["Transaction and provider reference", "GlyphBucks serial and liability event", "Journal and payout evidence", "Settlement and exception record"],
    handoff: "Reconciled value records move to management review, reporting, audit, and authorized providers.",
    maturity: "Implemented",
    statusNote: "Operational recordkeeping; not banking or acquiring",
    modules: ["GlyphBucks", "Ledgers", "Payout evidence", "Reconciliation", "Timestamp proof"],
    links: [
      { label: "GlyphLock Financial", to: "/GlyphLockFinancial" },
      { label: "Blockchain evidence", to: "/Blockchain" },
      { label: "NUPS value flow", to: "/NUPSLanding#nups-architecture" },
    ],
  },
  {
    id: "integration",
    number: "06",
    label: "Integration & Delivery",
    short: "Integration",
    color: "#C084FC",
    problem: "External systems need controlled interoperability that preserves authorization, auditability, customer ownership, and provider responsibility.",
    inputs: ["Authorized applications and credentials", "Defined data boundaries", "Provider or customer approval", "Hardware and venue requirements"],
    actions: ["Invoke SDK, API, webhook, or backend functions", "Validate keys, permissions, rate, and payload", "Exchange permitted records", "Configure hardware, deployment, and training"],
    records: ["API and usage event", "Connector or provider reference", "Structured response", "Deployment and audit context"],
    handoff: "Verified results return to the calling application or continue into an authorized GlyphLock workflow.",
    maturity: "Integration work",
    statusNote: "Availability and approval verified per integration",
    modules: ["SDK", "API keys", "Webhooks", "Provider adapters", "OHIP", "Hardware"],
    links: [
      { label: "SDK documentation", to: "/SDKDocs" },
      { label: "NUPS integrations", to: "/NUPSLanding#nups-integrations" },
      { label: "OHIP readiness", to: "/OHIPReadiness" },
      { label: "Deployment services", to: "/Services" },
    ],
  },
];

export const technicalSystems = [
  {
    id: "auto-dj",
    eyebrow: "Automated venue media",
    title: "Automated DJ + Fable visual engine",
    summary: "A working venue-media system that plans playlists, resolves playable sources, prepares the next deck, blends tracks, exposes crowd controls, and drives a separate beat-reactive visual stage.",
    flow: [
      "Search, upload, playlist, or track-library input",
      "AI-assisted playlist and transition planning",
      "Provider-aware source resolution",
      "Dual-deck cueing and next-track preparation",
      "Equal-power crossfade with configurable blend timing",
      "Playback telemetry, diagnostics, and Fable visuals",
    ],
    proof: ["AI playlist generator", "YouTube and direct-audio paths", "Local track library", "Dual player decks", "Auto-DJ promotion logic", "Crowd tools", "Fable stage"],
    maturity: "Active development",
    statusNote: "Working product surfaces with continuing venue hardening",
    color: "#F5B942",
    links: [
      { label: "Open DJ Pro Mixer", to: "/GlyphBotMixer" },
      { label: "Open Fable Stage", to: "/FableStage" },
    ],
  },
  {
    id: "stego",
    eyebrow: "Concealed and interactive media",
    title: "Steganographic images + interactive hotspots",
    summary: "Two complementary image systems: supported LSB experiments place recoverable machine-readable context into selected pixel bits, while interactive images attach typed actions to responsive hotspot regions.",
    flow: [
      "Select a source image and permitted payload",
      "Encode supported LSB data or map hotspot regions",
      "Attach coordinates, actions, hash, and provenance context",
      "Finalize a protected or interactive asset",
      "Share, view, export, decode, or verify through the authorized path",
    ],
    proof: ["Encode/decode functions", "ProtectedEvidence records", "Hotspot maps", "Typed hotspot payloads", "Interactive viewer", "Share and export workflows"],
    maturity: "Implemented + research",
    statusNote: "Hotspots implemented; concealed carrier remains unreleased",
    color: "#8C4BFF",
    links: [
      { label: "Open Image Lab", to: "/ImageLab" },
      { label: "Interactive Image Studio", to: "/InteractiveImageStudio" },
    ],
  },
  {
    id: "secure-qr",
    eyebrow: "Structured machine-readable carriers",
    title: "Secure QR generation, scanning, and verification",
    summary: "A structured carrier system with exactly 91 current payload definitions, versioned assets, validation paths, scan-event evidence, analytics, and dispatch into connected workflows.",
    flow: ["Define", "Generate", "Distribute", "Scan", "Validate", "Log", "Dispatch", "Review"],
    proof: ["QR asset and key registries", "Secure token generation", "Validation and tamper checks", "Risk evaluation", "Scan-event logging", "Analytics", "Barcode generation"],
    maturity: "Implemented",
    statusNote: "Working catalog and verification surfaces",
    color: "#00E4FF",
    links: [
      { label: "Open Secure QR Studio", to: "/SecureQRStudio" },
      { label: "Read QR SDK guidance", to: "/SDKDocs#qr" },
    ],
  },
  {
    id: "developer-rail",
    eyebrow: "Developer and enterprise rail",
    title: "SDK, API, webhook, provider, and hardware integration",
    summary: "Controlled integration surfaces connect authorized applications, backend functions, QR operations, audit events, provider adapters, hospitality systems, and physical devices without erasing provider boundaries.",
    flow: [
      "Authorized application, key, connector, or device",
      "SDK method, API request, webhook, or backend function",
      "Permission, payload, rate, and environment validation",
      "Governed workflow and audit event",
      "Structured response returned to the caller",
    ],
    proof: ["JavaScript, Python, and Go materials", "API key lifecycle", "API references", "Gateway functions", "Webhook handlers", "Connector configuration", "OHIP partner-sandbox path"],
    maturity: "Integration work",
    statusNote: "Production availability and external approval verified individually",
    color: "#C084FC",
    links: [
      { label: "Read SDK documentation", to: "/SDKDocs" },
      { label: "See NUPS integrations", to: "/NUPSLanding#nups-integrations" },
      { label: "Review OHIP readiness", to: "/OHIPReadiness" },
    ],
  },
];

export const scenarios = [
  {
    id: "venue",
    label: "Venue night",
    title: "From arrival to management review",
    color: "#34D399",
    steps: [
      { label: "Venue context", actor: "Operator", system: "NUPS", record: "Venue · session · mode" },
      { label: "Identity", actor: "Guest + door", system: "Front Door", record: "Profile · age-gate result" },
      { label: "Authorization", actor: "Role engine", system: "Access controls", record: "Role · permission · scope" },
      { label: "Agreement", actor: "Parties", system: "Contracts", record: "Terms · signatures · approval" },
      { label: "Transaction", actor: "Operator", system: "Register", record: "Tender · amount · provider reference" },
      { label: "Close", actor: "Management", system: "Batch + reconciliation", record: "Reports · exceptions · audit" },
    ],
  },
  {
    id: "creative",
    label: "Creative asset",
    title: "From image to reviewable interaction",
    color: "#8C4BFF",
    steps: [
      { label: "Source", actor: "Creator", system: "Image Lab", record: "Asset · ownership context" },
      { label: "Activate", actor: "Creator", system: "Carrier tools", record: "Payload or hotspot map" },
      { label: "Connect", actor: "System", system: "Secure QR", record: "Version · destination · token" },
      { label: "Distribute", actor: "Publisher", system: "Share workflow", record: "Share reference" },
      { label: "Interact", actor: "Viewer", system: "Scanner or viewer", record: "Scan or interaction event" },
      { label: "Review", actor: "Authorized reviewer", system: "Evidence tools", record: "Provenance · activity context" },
    ],
  },
  {
    id: "enterprise",
    label: "Enterprise integration",
    title: "From external request to governed response",
    color: "#C084FC",
    steps: [
      { label: "Request", actor: "External system", system: "SDK or API", record: "Method · payload · request ID" },
      { label: "Authenticate", actor: "Gateway", system: "Key or connector", record: "Identity · scope · environment" },
      { label: "Validate", actor: "Policy", system: "Security controls", record: "Allow or block decision" },
      { label: "Execute", actor: "Backend", system: "Governed function", record: "Business event" },
      { label: "Audit", actor: "Platform", system: "Evidence core", record: "Actor · decision · outcome" },
      { label: "Respond", actor: "GlyphLock", system: "Integration rail", record: "Structured response" },
    ],
  },
];

export const maturityGroups = [
  {
    label: "Implemented",
    color: "#00E4FF",
    description: "Exists in the current codebase and can be demonstrated.",
    items: ["Secure QR catalog", "Image Lab and hotspots", "GlyphBot surfaces", "NUPS workflows", "GlyphBucks and ledgers", "Audit and reconciliation surfaces"],
  },
  {
    label: "Operational proof",
    color: "#34D399",
    description: "Hardware-tested or used in a real operating environment.",
    items: ["NUPS front-door workflows", "Role-based venue operations", "Contracts and register records", "Real venue hardware testing"],
  },
  {
    label: "Integration work",
    color: "#C084FC",
    description: "Built or tested interoperability; not endorsement or production approval.",
    items: ["OHIP partner-sandbox path", "Payment-provider adapters", "SDK and API materials", "Storage, analytics, and hardware rails"],
  },
  {
    label: "Research and internal standards",
    color: "#F5B942",
    description: "GlyphLock-authored experiments, methods, and unreleased technology.",
    items: ["Concealed-image carrier direction", "Master Covenant", "AI-governance experiments", "Broader provenance portability"],
  },
];

export const leadership = [
  {
    name: "Carlo Rene Earl",
    title: "Founder & Chief Executive Officer",
    body: "Leads product architecture, intellectual-property strategy, integration direction, and the translation of firsthand creative and venue problems into connected systems.",
    to: "/AboutCarlo",
  },
  {
    name: "Collin Vanderginst",
    title: "Chief Technology Officer",
    body: "Responsible for engineering direction, technical execution, system hardening, and the delivery discipline required to move product concepts into dependable software.",
  },
  {
    name: "Jacub Lough",
    title: "Chief Financial Officer & Chief Strategy Officer",
    body: "Leads financial strategy, underwriting and partner coordination, risk positioning, and the commercial structure around GlyphLock deployments.",
  },
];
