// Demo receipt venue — mock header/branding used ONLY for demonstration
// receipts (transactions with mode === 'DEMO' or is_demo === true). Keeps demo
// output clearly labeled as a demonstration and never mixed with a live venue's
// real name, address, tax id, or footer. All values are fictional mock data.

export const DEMO_RECEIPT_VENUE = {
  venue_id: 'demo_venue',
  name: 'Dream Palace (DEMO)',
  legal_name: 'Dream Palace Demonstration Venue — SAMPLE',
  address: '1000 Demo Blvd',
  city: 'Sample City',
  state: 'AZ',
  phone: '(555) 000-DEMO',
  tax_id: 'DEMO-TAX-ID · NOT A REAL RECEIPT',
  footer_text:
    '★ DEMONSTRATION RECEIPT ★\nMock data — no real transaction occurred.\nGenerated by N.U.P.S. POS demo mode.',
};

// A transaction is a demo receipt when it carries a demo marker.
export const isDemoTransaction = (transaction) =>
  transaction?.mode === 'DEMO' ||
  transaction?.mode === 'SANDBOX' ||
  transaction?.is_demo === true ||
  transaction?.venue_id === 'demo_venue';