{
  "generatedAt": "2025-12-04",
  "version": "1.0.0",
  "pages": [
    {"route": "Home", "file": "pages/Home.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "About", "file": "pages/About.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "Accessibility", "file": "pages/Accessibility.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "BillingAndPayments", "file": "pages/BillingAndPayments.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Blockchain", "file": "pages/Blockchain.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "CommandCenter", "file": "pages/CommandCenter.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "Consultation", "file": "pages/Consultation.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "ConsultationSuccess", "file": "pages/ConsultationSuccess.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Contact", "file": "pages/Contact.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "ContentGenerator", "file": "pages/ContentGenerator.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Cookies", "file": "pages/Cookies.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "Dashboard", "file": "pages/Dashboard.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "DreamTeam", "file": "pages/DreamTeam.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "EntertainerCheckIn", "file": "pages/EntertainerCheckIn.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "FAQ", "file": "pages/FAQ.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "GlyphBot", "file": "pages/GlyphBot.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "GlyphBotJunior", "file": "pages/GlyphBotJunior.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "GovernanceHub", "file": "pages/GovernanceHub.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "HSSS", "file": "pages/HSSS.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "HotzoneMapper", "file": "pages/HotzoneMapper.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "ImageGenerator", "file": "pages/ImageGenerator.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "ImageLab", "file": "pages/ImageLab.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "IntegrationTests", "file": "pages/IntegrationTests.jsx", "navigationPresence": false, "productionReady": false, "archived": false},
    {"route": "InteractiveImageStudio", "file": "pages/InteractiveImageStudio.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "ManageSubscription", "file": "pages/ManageSubscription.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "MasterCovenant", "file": "pages/MasterCovenant.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "NotFound", "file": "pages/NotFound.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "NUPSLogin", "file": "pages/NUPSLogin.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "NUPSOwner", "file": "pages/NUPSOwner.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "NUPSStaff", "file": "pages/NUPSStaff.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Partners", "file": "pages/Partners.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "PaymentCancel", "file": "pages/PaymentCancel.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "PaymentSuccess", "file": "pages/PaymentSuccess.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Pricing", "file": "pages/Pricing.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "Privacy", "file": "pages/Privacy.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "ProviderConsole", "file": "pages/ProviderConsole.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Qr", "file": "pages/Qr.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "QrGenerator", "file": "pages/QrGenerator.jsx", "navigationPresence": false, "productionReady": true, "archived": true},
    {"route": "QrGeneratorAnalytics", "file": "pages/QrGeneratorAnalytics.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "QrGeneratorBulk", "file": "pages/QrGeneratorBulk.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "QrGeneratorCreate", "file": "pages/QrGeneratorCreate.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "QrGeneratorCustomize", "file": "pages/QrGeneratorCustomize.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "QrGeneratorHotzones", "file": "pages/QrGeneratorHotzones.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "QrGeneratorPreview", "file": "pages/QrGeneratorPreview.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "QrGeneratorSecurity", "file": "pages/QrGeneratorSecurity.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "QrGeneratorStego", "file": "pages/QrGeneratorStego.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Roadmap", "file": "pages/Roadmap.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "Robots", "file": "pages/Robots.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "SDKDocs", "file": "pages/SDKDocs.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "SecurityDocs", "file": "pages/SecurityDocs.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "SecurityOperationsCenter", "file": "pages/SecurityOperationsCenter.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "SecurityTools", "file": "pages/SecurityTools.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "Services", "file": "pages/Services.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Sitemap", "file": "pages/Sitemap.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "SitemapApp", "file": "pages/SitemapApp.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "SitemapDynamic", "file": "pages/SitemapDynamic.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "SitemapImages", "file": "pages/SitemapImages.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "SitemapInteractive", "file": "pages/SitemapInteractive.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "SitemapQr", "file": "pages/SitemapQr.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "SitemapXml", "file": "pages/SitemapXml.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Solutions", "file": "pages/Solutions.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "Steganography", "file": "pages/Steganography.jsx", "navigationPresence": false, "productionReady": true, "archived": true},
    {"route": "Terms", "file": "pages/Terms.jsx", "navigationPresence": true, "productionReady": true, "archived": false},
    {"route": "VIPContract", "file": "pages/VIPContract.jsx", "navigationPresence": false, "productionReady": true, "archived": false},
    {"route": "VisualCryptography", "file": "pages/VisualCryptography.jsx", "navigationPresence": false, "productionReady": true, "archived": true}
  ],
  "routingIntegrity": {
    "totalPages": 64,
    "navigablePages": 30,
    "orphanPages": 0,
    "missingPages": 0,
    "archivedPages": 0
  }
}