import { createClientFromRequest } from 'npm:@base44/sdk@0.8.21';

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me();

  if (!user) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const payload = await req.json();
  const {
    room_number,
    customer_name,
    customer_id,
    start_time,
    end_time,
    minimum_spend,
    staff_id
  } = payload;

  if (!room_number || !customer_name || !start_time || !minimum_spend) {
    return Response.json({
      success: false,
      error: 'Missing required fields: room_number, customer_name, start_time, minimum_spend'
    }, { status: 400 });
  }

  const contractUUID = crypto.randomUUID();
  const venueConfig = {
    name: 'The Dream Palace',
    legal_entity: 'Liberty Holding Group, L.L.C. dba The Dream Palace',
    address: '815 N. Scottsdale Road, Tempe, AZ 85281',
    phone: '(602) 536-0372'
  };

  const contractBody = `VIP ROOM SERVICE AGREEMENT

Contract ID: ${contractUUID}
Generated: ${new Date().toLocaleString('en-US', { timeZone: 'America/Phoenix' })}

VENUE INFORMATION
${venueConfig.legal_entity}
${venueConfig.address}
Phone: ${venueConfig.phone}

CUSTOMER INFORMATION
Name: ${customer_name}
ID Number: ${customer_id || 'Not provided'}

VIP ROOM DETAILS
Room Number: ${room_number}
Start Time: ${new Date(start_time).toLocaleString('en-US', { timeZone: 'America/Phoenix' })}
End Time: ${end_time ? new Date(end_time).toLocaleString('en-US', { timeZone: 'America/Phoenix' }) : 'Open-ended'}
Minimum Spend: $${minimum_spend.toFixed(2)}
Attendant: ${staff_id || 'Assigned by management'}

TERMS AND CONDITIONS

1. VIP Room Access
The customer ("Guest") is granted access to VIP Room ${room_number} for the duration specified above. Room access is contingent upon meeting the minimum spend requirement and compliance with all club policies.

2. Minimum Spend Requirement
Guest agrees to a minimum spend of $${minimum_spend.toFixed(2)} for use of the VIP room. This amount must be satisfied through purchase of club services, beverages, or GlyphBucks (club currency). Failure to meet minimum spend will result in a charge for the difference.

3. Independent Contractors
All entertainers at ${venueConfig.name} are independent contractors and not employees of the venue. Any arrangements between Guest and entertainers for services are independent agreements. The venue is not responsible for entertainer services or conduct.

4. Payment Terms
All charges are due immediately upon completion of service. Guest authorizes payment via the credit card on file. Any disputes must follow the dispute resolution process outlined in the venue's standard Terms of Service.

5. Conduct Policy
Guest agrees to comply with all club policies, local ordinances, and state regulations. Inappropriate conduct, harassment, or illegal activity will result in immediate ejection without refund.

6. Liability Waiver
Guest assumes all risk associated with VIP room services. The venue is not liable for any injuries, losses, or damages except as required by law.

By signing below, Guest acknowledges reading and accepting all terms.

_________________________________
Guest Signature

_________________________________
Staff Witness Signature

Contract Generated by: ${user.email}
System Timestamp: ${new Date().toISOString()}
`;

  const contractRecord = await base44.asServiceRole.entities.VIPContractRecord.create({
    order_number: contractUUID,
    guest_name: customer_name,
    venue_id: 'dream_palace',
    contract_type: 'vip_room_service',
    total_amount: minimum_spend,
    customer_signature: null,
    manager_signature: null,
    hostess_signature: null,
    status: 'active',
    contract_metadata: {
      room_number,
      customer_id,
      start_time,
      end_time,
      staff_id,
      generated_by: user.email,
      generated_at: new Date().toISOString()
    }
  });

  return Response.json({
    success: true,
    contract: {
      uuid: contractUUID,
      record_id: contractRecord.id,
      body: contractBody,
      customer_name,
      room_number,
      minimum_spend,
      status: 'active',
      generated_at: new Date().toISOString()
    }
  });
});