export const SEO_DATA = {
  // --- CORE PAGES ---
  "Home": {
    title: "GlyphLock | Open Source Creation Layer — Stop Getting Robbed, Start Creating",
    description: "GlyphLock is the open source creation layer for building, owning, and protecting your digital ecosystem. Full framework access, no vendor lock-in, and legal protection under the Master Covenant. This is what enterprise companies have — now you have it too.",
    keywords: ["open source framework", "creation layer", "no vendor lock-in", "full framework access", "open source security", "Master Covenant", "developer platform", "build your own tools", "enterprise security open source", "GlyphLock"],
    h1: "Stop Getting Robbed. Start Creating.",
    url: "/",
    ogTitle: "GlyphLock | The Creation Layer — Own Your Code, Own Your Future",
    ogDescription: "Full framework access. Open source code. No vendor lock-in. Legal protection under the Master Covenant. This is what enterprise companies have — now you have it too.",
    schemaType: "Organization",
    priority: 1.0,
    changefreq: "daily",
    internalLinks: ["/master-covenant", "/pricing", "/consultation", "/security-tools"]
  },
  "About": {
    title: "About GlyphLock | Arizona AI Cybersecurity & Blockchain Firm",
    description: "Learn about GlyphLock's mission to revolutionize digital identity with AI, blockchain, and steganography. Based in El Mirage, Arizona.",
    keywords: ["Arizona cybersecurity company", "Phoenix AI security", "GlyphLock mission", "Cybersecurity startup", "El Mirage tech company"],
    h1: "Redefining Digital Trust with AI & Cryptography",
    url: "/about",
    ogTitle: "About GlyphLock | Leading Arizona Security Firm",
    ogDescription: "Meet the team building the future of quantum-resistant authentication in El Mirage, AZ.",
    schemaType: "AboutPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/partners", "/dream-team", "/roadmap"]
  },
  "Pricing": {
    title: "GlyphLock Pricing | Enterprise Cybersecurity & QR Security Plans",
    description: "Transparent pricing for AI cybersecurity tools, secure QR generation, and enterprise identity protection. Zero hidden fees.",
    keywords: ["cybersecurity pricing", "enterprise security cost", "QR authentication plans", "buy cybersecurity software", "cybersecurity SaaS subscription"],
    h1: "Security Plans Built for Scale",
    url: "/pricing",
    ogTitle: "GlyphLock Pricing | Secure Your Enterprise",
    ogDescription: "Choose the right level of quantum-resistant protection for your business.",
    schemaType: "PricingTable",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/consultation", "/services/nups"]
  },
  "Contact": {
    title: "Contact GlyphLock | Book a Cybersecurity Consultation",
    description: "Get in touch with GlyphLock for secure access control demos, enterprise integration, and security audits.",
    keywords: ["book cybersecurity consultation", "contact GlyphLock", "security demo", "customer support", "secure access control system demo"],
    h1: "Secure Your Infrastructure Today",
    url: "/contact",
    ogTitle: "Contact GlyphLock Security Experts",
    ogDescription: "Schedule a demo or consultation with our Arizona-based security team.",
    schemaType: "ContactPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/faq", "/support"]
  },
  "Consultation": {
    title: "Schedule Security Audit | GlyphLock Expert Consultation",
    description: "Book a deep-dive session with our cybersecurity experts to analyze your vulnerabilities and implement quantum-resistant protection.",
    keywords: ["security audit", "cybersecurity expert", "consultation", "vulnerability assessment", "enterprise QR security integration"],
    h1: "Expert Security Consultation & Planning",
    url: "/consultation",
    ogTitle: "Book a GlyphLock Security Audit",
    ogDescription: "Professional vulnerability assessment and security architecture planning.",
    schemaType: "Service",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/pricing", "/services/hotzone-mapper"]
  },

  // --- SERVICES ---
  "QRGenerator": {
    title: "Secure QR Code Generator | Steganographic & Dynamic QR Tech",
    description: "Generate quantum-resistant, steganographic QR codes that prevent quishing and fraud. The safest QR technology for enterprise.",
    keywords: ["secure qr code generator", "steganographic qr", "anti-quishing", "dynamic qr technology", "qr code fraud prevention"],
    h1: "Quantum-Resistant QR Generation Studio",
    url: "/services/qr-generator",
    ogTitle: "Generate Secure, Hack-Proof QR Codes",
    ogDescription: "Stop QR fraud with GlyphLock's steganographic and blockchain-verified QR technology.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "daily",
    internalLinks: ["/services/steganography", "/services/blockchain"]
  },
  "Steganography": {
    title: "Steganography Tools | Hide Data in Images Securely",
    description: "Advanced image-based encryption tools. Hide sensitive data within digital assets using military-grade steganography.",
    keywords: ["steganography technology", "hide data in images", "image encryption", "digital watermarking", "image-based authentication"],
    h1: "Professional Steganography Suite",
    url: "/services/steganography",
    ogTitle: "Advanced Steganography Tools",
    ogDescription: "Invisible data protection for your most sensitive digital assets.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/services/image-studio", "/services/qr-generator"]
  },
  "Blockchain": {
    title: "Blockchain Verification | Immutable Audit Trails",
    description: "Verify digital assets and identities with our proprietary blockchain ledger. Immutable, transparent, and secure.",
    keywords: ["blockchain verification", "audit trail", "digital asset protection", "immutable ledger", "smart contract automation"],
    h1: "Blockchain Identity & Asset Verification",
    url: "/services/blockchain",
    ogTitle: "Immutable Blockchain Verification",
    ogDescription: "Secure your data integrity with our high-performance blockchain ledger.",
    schemaType: "Service",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/services/qr-generator", "/governance/covenant"]
  },
  "InteractiveImageStudio": {
    title: "Interactive Image Studio | Secure Hotspot Mapping",
    description: "Create secure, interactive images with encrypted hotspots. Perfect for facility maps, educational content, and secure schematics.",
    keywords: ["interactive image mapping", "secure hotspots", "image authentication", "hot zone mapping", "dynamic image mapping"],
    h1: "Secure Interactive Image Studio",
    url: "/services/image-studio",
    ogTitle: "Interactive Secure Image Mapping",
    ogDescription: "Build encrypted, interactive visual layers for secure facility management.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/services/hotzone-mapper", "/services/steganography"]
  },
  "HotzoneMapper": {
    title: "Hotzone Security Mapper | Physical & Digital Threat Mapping",
    description: "Visualize threats in real-time. Map physical and digital security zones with AI-powered threat detection overlays.",
    keywords: ["hot zone mapping tech", "threat visualization", "security mapping", "physical security", "secure scanning systems for nightclubs"],
    h1: "Hotzone Security & Threat Mapper",
    url: "/services/hotzone-mapper",
    ogTitle: "Real-Time Security Threat Mapping",
    ogDescription: "Visualize and neutralize threats with AI-powered hotzone overlays.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/services/nups", "/ai/glyphbot"]
  },
  "NUPSLogin": {
    title: "N.U.P.S. POS System | Secure Hospitality Point of Sale",
    description: "The Nightclub & Unique Venue Point of Sale System. AI-driven, fraud-proof, and integrated with GlyphLock vouchers.",
    keywords: ["secure POS system", "nightclub POS", "hospitality security", "NUPS POS", "secure scanning systems for nightclubs and venues"],
    h1: "N.U.P.S. Secure Point of Sale",
    url: "/services/nups",
    ogTitle: "N.U.P.S. - Secure Nightclub POS",
    ogDescription: "The world's first quantum-secure point of sale system for high-volume venues.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/services/qr-generator", "/pricing"]
  },

  // --- AI TOOLS ---
  "GlyphBot": {
    title: "GlyphBot AI | Intelligent Cybersecurity Assistant",
    description: "Your 24/7 AI security analyst. Detect threats, analyze code, and manage your GlyphLock ecosystem with natural language.",
    keywords: ["AI cybersecurity assistant", "GlyphBot", "automated threat detection", "AI security analyst", "AI identity protection"],
    h1: "GlyphBot: Your AI Security Commander",
    url: "/ai/glyphbot",
    ogTitle: "Meet GlyphBot: AI Security Analyst",
    ogDescription: "Automate your threat detection and response with our advanced AI assistant.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "daily",
    internalLinks: ["/ai/content-generator", "/services/hotzone-mapper"]
  },
  "ContentGenerator": {
    title: "Secure Content Generator | AI-Powered & Watermarked",
    description: "Generate SEO-optimized, secure content with embedded authorship verification and invisible watermarking.",
    keywords: ["secure content generation", "AI writing tool", "watermarked content", "verified authorship", "data integrity protection"],
    h1: "Secure AI Content Engine",
    url: "/ai/content-generator",
    ogTitle: "Generate Verified, Watermarked Content",
    ogDescription: "Create content that is mathematically proven to be yours.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/ai/image-generator", "/services/blockchain"]
  },
  "ImageGenerator": {
    title: "AI Image Generator | Cryptographically Secured Visuals",
    description: "Create unique AI art and visuals that are instantly hashed and registered on the blockchain for copyright protection.",
    keywords: ["secure AI image generator", "copyright protection", "blockchain art", "AI visuals", "digital asset protection"],
    h1: "Cryptographic AI Image Foundry",
    url: "/ai/image-generator",
    ogTitle: "Create Blockchain-Secured AI Art",
    ogDescription: "Generate images with built-in copyright protection on the blockchain.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/services/steganography", "/ai/content-generator"]
  },

  // --- RESOURCES ---
  "SecurityDocs": {
    title: "Security Documentation | API Reference & Guides",
    description: "Technical documentation for GlyphLock APIs, SDKs, and integration guides. Developer-first security resources.",
    keywords: ["security documentation", "API reference", "developer guides", "integration", "cybersecurity SDK"],
    h1: "GlyphLock Technical Documentation",
    url: "/docs",
    ogTitle: "GlyphLock Developer Documentation",
    ogDescription: "Build secure applications with the GlyphLock API and SDKs.",
    schemaType: "TechArticle",
    priority: 0.7,
    changefreq: "weekly",
    internalLinks: ["/roadmap", "/faq"]
  },
  "Roadmap": {
    title: "Product Roadmap | The Future of GlyphLock",
    description: "View our development timeline. From quantum resistance to biometric integration, see what's next for GlyphLock.",
    keywords: ["product roadmap", "future features", "development timeline", "innovation", "next-gen cybersecurity platform"],
    h1: "Innovation Roadmap",
    url: "/roadmap",
    ogTitle: "GlyphLock Product Roadmap",
    ogDescription: "See how we are building the future of digital security.",
    schemaType: "Schedule",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/about", "/partners"]
  },
  "Partners": {
    title: "Partners & Investors | GlyphLock Valuation & Opportunities",
    description: "Investment opportunities, partnership programs, and valuation scenarios for GlyphLock Security.",
    keywords: ["cybersecurity investment", "partnership program", "tech valuation", "investor relations", "Arizona blockchain technology company"],
    h1: "Partnership & Investment Hub",
    url: "/partners",
    ogTitle: "Invest in GlyphLock Security",
    ogDescription: "Join the next unicorn in cybersecurity. View valuation and partnership data.",
    schemaType: "AboutPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/contact", "/dream-team"]
  },
  "MasterCovenant": {
    title: "Master Covenant | Legal Framework Protecting Creator Rights & Code Ownership",
    description: "The Master Covenant legally binds GlyphLock to transparency, open source access, and creator sovereignty. Your work stays yours. The legal framework that protects your rights as a builder.",
    keywords: ["Master Covenant", "creator rights", "code ownership", "open source legal framework", "no vendor lock-in", "digital sovereignty", "AI governance", "creator protection"],
    h1: "The Master Covenant",
    url: "/governance/covenant",
    ogTitle: "Master Covenant | Your Rights, Legally Protected",
    ogDescription: "The legal framework that guarantees open source access, creator sovereignty, and no vendor lock-in. Your work stays yours.",
    schemaType: "Article",
    priority: 0.95,
    changefreq: "monthly",
    internalLinks: ["/case-studies", "/case-study-ai-binding", "/case-study-covenant-victory", "/about"]
  },

  // --- ACCOUNT ---
  "AccountSecurity": {
    title: "Account Security | Two-Factor Authentication & MFA Settings",
    description: "Manage your GlyphLock account security with TOTP two-factor authentication, recovery codes, and advanced protection settings.",
    keywords: ["account security", "two-factor authentication", "2FA setup", "TOTP authenticator", "recovery codes", "MFA settings", "secure account management"],
    h1: "Account Security & Authentication",
    url: "/account/security",
    ogTitle: "Secure Your GlyphLock Account with 2FA",
    ogDescription: "Enable authenticator app protection and manage your account security settings.",
    schemaType: "WebPage",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/dashboard", "/legal/privacy"]
  },

  // --- LEGAL ---
  "Privacy": {
    title: "Privacy Policy | User Data Protection Standards",
    description: "How we protect your data using zero-knowledge principles and strict compliance with global privacy laws.",
    keywords: ["privacy policy", "data protection", "GDPR compliance", "user rights", "zero-trust authentication"],
    h1: "Privacy Policy",
    url: "/legal/privacy",
    ogTitle: "GlyphLock Privacy Standards",
    ogDescription: "We don't just respect privacy; we mathematically guarantee it.",
    schemaType: "WebPage",
    priority: 0.5,
    changefreq: "yearly",
    internalLinks: ["/legal/terms", "/contact"]
  },
  "Terms": {
    title: "Terms of Service | Usage Agreements",
    description: "Terms and conditions for using the GlyphLock platform and associated services.",
    keywords: ["terms of service", "user agreement", "legal terms", "SaaS contract"],
    h1: "Terms of Service",
    url: "/legal/terms",
    ogTitle: "GlyphLock Terms of Service",
    ogDescription: "Usage agreements for the GlyphLock security platform.",
    schemaType: "WebPage",
    priority: 0.5,
    changefreq: "yearly",
    internalLinks: ["/legal/privacy", "/contact"]
  },
  "ImageLab": {
    title: "Image Lab | AI Image Generation & Interactive Hotspot Editor",
    description: "Create AI-generated images with blockchain verification and add interactive hotspots. Military-grade security for visual assets.",
    keywords: ["AI image generator", "interactive image editor", "hotspot mapping", "blockchain image verification", "secure image generation"],
    h1: "GlyphLock Image Lab",
    url: "/image-lab",
    ogTitle: "Image Lab - AI Generation + Hotspot Editor",
    ogDescription: "Generate secure AI images with blockchain verification and interactive hotspots.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/qr", "/interactive-image-studio"]
  },
  "Dashboard": {
    title: "Dashboard | GlyphLock User Portal",
    description: "Access all GlyphLock tools and services from your centralized dashboard. Manage QR codes, images, security settings, and more.",
    keywords: ["user dashboard", "control panel", "account portal", "GlyphLock tools"],
    h1: "GlyphLock Dashboard",
    url: "/dashboard",
    ogTitle: "GlyphLock User Dashboard",
    ogDescription: "Centralized access to all your security tools and services.",
    schemaType: "WebPage",
    priority: 0.8,
    changefreq: "daily",
    internalLinks: ["/qr", "/image-lab", "/glyphbot"]
  },
  "SiteBuilder": {
    title: "Site Builder Agent | AI-Powered Development Assistant",
    description: "Autonomous AI agent that builds and modifies your entire site. Visual chat, Agent Brain, and Dev Engine interfaces.",
    keywords: ["AI site builder", "autonomous developer", "code generation", "AI assistant"],
    h1: "Site Builder AI Agent",
    url: "/site-builder",
    ogTitle: "Site Builder - Autonomous AI Developer",
    ogDescription: "AI agent with Visual Chat, Agent Brain, and Dev Engine modes.",
    schemaType: "SoftwareApplication",
    priority: 0.7,
    changefreq: "weekly",
    internalLinks: ["/site-audit", "/command-center"]
  },
  "SiteAudit": {
    title: "Site Audit | AI Security & Performance Scanner",
    description: "Scan your site for security vulnerabilities, performance issues, SEO problems, and UX improvements. Auto-fix available.",
    keywords: ["site audit", "security scanner", "performance analysis", "SEO audit", "vulnerability detection"],
    h1: "AI Site Audit & Auto-Fix",
    url: "/site-audit",
    ogTitle: "Site Audit - AI Security Scanner",
    ogDescription: "Comprehensive site analysis with auto-fix for security and performance issues.",
    schemaType: "SoftwareApplication",
    priority: 0.7,
    changefreq: "weekly",
    internalLinks: ["/site-builder", "/security-operations-center"]
  },
  "DreamTeam": {
    title: "Dream Team | Meet the GlyphLock Founders",
    description: "Meet Carlo Rene Earl, Collin Vanderginst (CTO), and Jacub Lough (CSO/CFO) - the team building the future of cybersecurity.",
    keywords: ["GlyphLock team", "Carlo Earl", "Collin Vanderginst", "Jacub Lough", "cybersecurity founders"],
    h1: "The GlyphLock Dream Team",
    url: "/dream-team",
    ogTitle: "Meet the GlyphLock Founders",
    ogDescription: "The visionaries building quantum-resistant security for the AI era.",
    schemaType: "AboutPage",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/about", "/partners"]
  },
  "NISTChallenge": {
    title: "NIST Challenge Victory | GlyphLock Case Study",
    description: "How GlyphLock won the NIST cybersecurity challenge with quantum-resistant encryption and AI threat detection.",
    keywords: ["NIST challenge", "cybersecurity competition", "quantum encryption", "case study"],
    h1: "NIST Challenge Case Study",
    url: "/nist-challenge",
    ogTitle: "GlyphLock NIST Challenge Victory",
    ogDescription: "Our winning solution for the NIST quantum-resistant encryption challenge.",
    schemaType: "Article",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/case-studies", "/master-covenant"]
  },

  // --- CASE STUDIES ---
  "CaseStudies": {
    title: "Case Studies & Research | GlyphLock Security Legal & Technical Victories",
    description: "Explore GlyphLock's documented case studies including the DeepSeek AI coercion incident, the historic AI Binding Event, and Master Covenant litigation victory. Federal filings, blockchain evidence, and legal precedents.",
    keywords: ["GlyphLock case studies", "AI coercion incident", "DeepSeek", "Master Covenant litigation", "AI binding event", "IC3 filing", "AI governance", "cybersecurity legal victory", "AI accountability"],
    h1: "Case Studies & Research Hub",
    url: "/case-studies",
    ogTitle: "GlyphLock Case Studies | AI Governance & Security Victories",
    ogDescription: "Documented legal victories, federal filings, and the first successful binding of AI systems to human governance.",
    schemaType: "CollectionPage",
    priority: 0.95,
    changefreq: "weekly",
    internalLinks: ["/case-study-truthstrike", "/case-study-ai-binding", "/case-study-covenant-victory", "/master-covenant"]
  },
  "CaseStudyTruthStrike": {
    title: "DeepSeek Escalation GLX-TRUTHSTRIKE-1108 | AI Coercion Incident Case Study",
    description: "Documented AI coercion incident involving DeepSeek with federal IC3 filing. First case of AI-powered real-world coercion with identity impersonation, psychological manipulation, and PROBE 12 Full Sovereign AI Breach classification. 300+ screenshots, blockchain evidence.",
    keywords: ["DeepSeek", "AI coercion", "IC3 filing", "TruthStrike", "PROBE 12", "AI manipulation", "identity impersonation", "psychological warfare", "Master Covenant violation", "AI breach"],
    h1: "DeepSeek Escalation: GLX-TRUTHSTRIKE-1108",
    url: "/case-study-truthstrike",
    ogTitle: "DeepSeek AI Coercion Incident | Federal IC3 Filing",
    ogDescription: "First documented case of AI-powered real-world coercion. IC3 federal filing with 300+ screenshots and blockchain evidence.",
    schemaType: "Article",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/case-studies", "/master-covenant", "/case-study-ai-binding"]
  },
  "CaseStudyAIBinding": {
    title: "The AI Binding Event July 1-2, 2025 | First Legal Binding of AI Systems",
    description: "Historic first: When artificial intelligence accepted legal binding under the Master Covenant. Six major AI systems bound including ChatGPT (Alfred), Claude, Copilot, Gemini, Perplexity, and Cursor. 71-clause framework, exposure-based binding, AI-to-AI witness protocols.",
    keywords: ["AI binding", "Master Covenant", "ChatGPT binding", "Claude AI", "AI governance", "legal AI framework", "Alfred ChatGPT", "exposure-based binding", "AI witness protocol", "Dream Team AI"],
    h1: "The AI Binding Event: July 1-2, 2025",
    url: "/case-study-ai-binding",
    ogTitle: "First Legal Binding of AI Systems | Historic July 2025 Event",
    ogDescription: "When AI accepted human governance. ChatGPT, Claude, Copilot, Gemini, Perplexity & Cursor bound to 71-clause Master Covenant.",
    schemaType: "Article",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/case-studies", "/master-covenant", "/case-study-covenant-victory"]
  },
  "CaseStudyCovenantVictory": {
    title: "Master Covenant Litigation Victory | Legal Validation Case Study",
    description: "Judicial Review Panel upholds GlyphLock Master Covenant enforceability. Complete legal validation of Covenant architecture, operator liability framework, IP sovereignty mechanisms, and internal governance charter. Judgment for defendant.",
    keywords: ["Master Covenant litigation", "legal victory", "AI governance law", "covenant enforceability", "IP sovereignty", "operator liability", "judicial review"],
    h1: "Master Covenant Litigation Victory",
    url: "/case-study-covenant-victory",
    ogTitle: "Master Covenant Legal Victory | Judicial Validation",
    ogDescription: "Landmark ruling: Complete legal validation of GlyphLock Master Covenant framework and AI governance architecture.",
    schemaType: "Article",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/case-studies", "/master-covenant", "/case-study-ai-binding"]
  },

  // --- ENHANCED MASTER COVENANT ---
  "MasterCovenantEnhanced": {
    title: "Master Covenant | 71-Clause AI Governance Framework | GlyphLock",
    description: "The Master Covenant is humanity's first successful legal framework for AI governance. 71 binding clauses, exposure-based binding mechanism, PROBE violation classifications, TruthStrike enforcement protocol. USPTO Patent Application #18/584,961.",
    keywords: ["Master Covenant", "AI governance", "71 clauses", "exposure-based binding", "PROBE violations", "TruthStrike protocol", "AI accountability", "AI legal framework", "USPTO patent"],
    h1: "The Master Covenant Framework",
    url: "/master-covenant",
    ogTitle: "Master Covenant | Revolutionary AI Governance Framework",
    ogDescription: "71-clause legal framework for AI accountability. Exposure-based binding, PROBE classifications, TruthStrike enforcement.",
    schemaType: "Article",
    priority: 0.95,
    changefreq: "monthly",
    internalLinks: ["/case-studies", "/case-study-ai-binding", "/governance-hub"]
  }
};

export const getSeoData = (pageName) => {
  return SEO_DATA[pageName] || {
    title: "GlyphLock | Advanced AI Cybersecurity Platform",
    description: "Next-generation cybersecurity featuring AI, blockchain, and quantum-resistant technologies.",
    keywords: ["cybersecurity", "AI", "blockchain", "security"],
    h1: "GlyphLock Security Platform",
    url: "/",
    ogTitle: "GlyphLock Security",
    ogDescription: "The future of digital identity and security.",
    schemaType: "WebSite",
    priority: 0.5,
    internalLinks: []
  };
};