// ============================================================================
// seoData.jsx — CANONICAL RUNTIME SOURCE OF TRUTH for GlyphLock SEO metadata.
// ----------------------------------------------------------------------------
// Rules (enforced by scripts/check-seo-metadata.mjs):
//  - One entry per real public route. URLs use ACTUAL route casing from
//    pages.config.js / App.jsx (e.g. /SecureQRStudio, /ImageLab, /GlyphBot,
//    /NUPSLanding, /SDKDocs, /GlyphLockFinancial). No obsolete service slugs.
//  - No retired/misleading strings (full enumerated list enforced by
//    scripts/check-seo-metadata.mjs).
//  - NUPS expands to "Nexus Unified POS System" only.
//  - Structured data is claims-safe: no unsupported certification, endorsement,
//    price, rating, partner, patent, or production claims.
//  - Canonical origin: https://glyphlock.io
// ============================================================================

export const CANONICAL_ORIGIN = "https://glyphlock.io";

export const CANONICAL_POSITIONING_LINE = "GlyphLock connects identity and permission, secure QR and image carriers, AI-assisted workflows, NUPS venue operations, financial accountability, APIs, hardware, and governance through one evidence architecture.";

// Global fallback keyword set — also used for the Home page.
export const GLOBAL_FALLBACK_KEYWORDS = [
  "GlyphLock",
  "evidence infrastructure",
  "identity and permission workflows",
  "Secure QR",
  "interactive images",
  "GlyphBot",
  "automated DJ",
  "NUPS",
  "venue operations software",
  "financial accountability",
  "API and SDK integration",
  "governance",
];

export const SEO_DATA = {
  // ─────────────────────────── CORE PAGES ───────────────────────────
  "Home": {
    title: "GlyphLock | Evidence Infrastructure for Identity & Proof",
    description: "Evidence infrastructure for identity, operations, and proof. Secure QR, verified access, and financial accountability in one auditable system.",
    keywords: [...GLOBAL_FALLBACK_KEYWORDS],
    h1: "Build. Verify. Operate.",
    positioningLine: CANONICAL_POSITIONING_LINE,
    url: "/",
    ogTitle: "GlyphLock | Evidence Infrastructure for Identity & Proof",
    ogDescription: "Evidence infrastructure for identity, operations, and proof. Secure QR, verified access, and financial accountability in one auditable system.",
    schemaType: "Organization",
    priority: 1.0,
    changefreq: "daily",
    internalLinks: ["/About", "/SecureQRStudio", "/GlyphBot", "/NUPSLanding", "/Services", "/Consultation"],
  },
  "About": {
    title: "About GlyphLock | Technology, NUPS & Evidence Architecture",
    description: "GlyphLock builds evidence infrastructure connecting identity, permissions, and financial accountability. Founded 2025 in El Mirage, Arizona.",
    keywords: [
      "GlyphLock", "evidence infrastructure", "identity and permission workflows", "Secure QR Studio",
      "QR verification", "interactive images", "image carrier research", "GlyphBot", "automated DJ software",
      "Fable visual engine", "NUPS", "Nexus Unified POS System", "venue operations software", "digital contracts",
      "GlyphBucks", "closed-loop stored value", "reconciliation", "API integration", "SDK integration", "webhooks",
      "hardware integration", "Oracle Hospitality integration", "OHIP integration work", "audit trails", "governance",
      "Carlo Rene Earl", "Jacub Lough", "Collin Vanderginst", "El Mirage Arizona",
    ],
    h1: "Identity. Permission. Operations. Proof.",
    url: "/About",
    ogTitle: "About GlyphLock | Technology, NUPS & Evidence Architecture",
    ogDescription: "GlyphLock builds evidence infrastructure connecting identity, permissions, and financial accountability. Founded 2025 in El Mirage, Arizona.",
    schemaType: "AboutPage",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/ImageLab", "/InteractiveImageStudio", "/GlyphBot", "/GlyphBotMixer", "/NUPSLanding", "/GlyphLockFinancial", "/GovernanceHub", "/SecurityOperationsCenter", "/SDKDocs", "/AboutCarlo", "/Consultation"],
  },
  "AboutCarlo": {
    title: "Carlo René Earl | GlyphLock Founder & NUPS Creator",
    description: "Meet Carlo René Earl, founder of GlyphLock and creator of NUPS, and trace how venue operations shaped its identity, agreement, and audit workflows.",
    keywords: ["Carlo René Earl", "Carlo Rene Earl", "GlyphLock founder", "NUPS creator", "GlyphLock product architect", "venue operations founder", "hospitality technology", "transaction evidence", "identity workflows", "Arizona technology founder"],
    h1: "This Is Not a Resume",
    url: "/AboutCarlo",
    ogTitle: "Carlo René Earl | GlyphLock Founder & NUPS Creator",
    ogDescription: "Meet Carlo René Earl, founder of GlyphLock and creator of NUPS, and trace how venue operations shaped its identity, agreement, and audit workflows.",
    schemaType: "ProfilePage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/About", "/Partners", "/Contact", "/Consultation"],
  },
  "Pricing": {
    title: "GlyphLock Plans | Evidence Infrastructure & NUPS",
    description: "GlyphLock pricing for Secure QR, NUPS venue operations, and API access. Plans for single venues through multi-site operators.",
    keywords: ["GlyphLock pricing", "evidence infrastructure plans", "Secure QR plans", "NUPS access", "GlyphBot access", "venue operations software"],
    h1: "Plans for Connected Evidence and Operations",
    url: "/Pricing",
    ogTitle: "GlyphLock Plans | Evidence Infrastructure & NUPS",
    ogDescription: "GlyphLock pricing for Secure QR, NUPS venue operations, and API access. Plans for single venues through multi-site operators.",
    schemaType: "PricingTable",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/Consultation", "/Services"],
  },
  "Contact": {
    title: "Contact GlyphLock | Product & Deployment Consultation",
    description: "Contact GlyphLock LLC in El Mirage, Arizona for demos, partnerships, and integration questions.",
    keywords: ["contact GlyphLock", "GlyphLock consultation", "NUPS deployment", "Secure QR integration", "GlyphBot", "API integration"],
    h1: "Discuss a GlyphLock Deployment",
    url: "/Contact",
    ogTitle: "Contact GlyphLock | Product & Deployment Consultation",
    ogDescription: "Contact GlyphLock LLC in El Mirage, Arizona for demos, partnerships, and integration questions.",
    schemaType: "ContactPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/FAQ", "/Consultation"],
  },
  "Consultation": {
    title: "GlyphLock Architecture Consultation | Plan a Deployment",
    description: "Map a GlyphLock deployment across image carriers, Secure QR, GlyphBot, NUPS, identity and contract workflows, ledgers, SDKs, APIs, and integrations.",
    keywords: ["GlyphLock architecture consultation", "NUPS deployment planning", "Secure QR workflow", "SDK integration", "API integration", "venue systems"],
    h1: "Plan a Connected GlyphLock Deployment",
    url: "/Consultation",
    ogTitle: "GlyphLock Architecture Consultation | Plan a Deployment",
    ogDescription: "Map a GlyphLock deployment across image carriers, Secure QR, GlyphBot, NUPS, identity and contract workflows, ledgers, SDKs, APIs, and integrations.",
    schemaType: "Service",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/Pricing", "/Services"],
  },
  "Services": {
    title: "GlyphLock Services | Software & Systems Integration",
    description: "GlyphLock services span custom software, system integration, AI engineering, operations software, and deployment support for connected evidence workflows.",
    keywords: ["GlyphLock services", "custom software", "system integration", "AI engineering", "operations software", "deployment support"],
    h1: "Services for Connected Evidence and Operations",
    url: "/Services",
    ogTitle: "GlyphLock Services | Software & Systems Integration",
    ogDescription: "GlyphLock services span custom software, system integration, AI engineering, operations software, and deployment support for connected evidence workflows.",
    schemaType: "Service",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/Consultation", "/Solutions"],
  },
  "Solutions": {
    title: "GlyphLock Solutions | Identity, Operations & Proof",
    description: "Identity and permission workflows, secure QR carriers, venue operations, and API integration — built on a single evidence architecture.",
    keywords: ["GlyphLock solutions", "identity workflows", "Secure QR", "interactive images", "NUPS operations", "financial records", "governance"],
    h1: "Solution Patterns for Connected Workflows",
    url: "/Solutions",
    ogTitle: "GlyphLock Solutions | Identity, Operations & Proof",
    ogDescription: "Identity and permission workflows, secure QR carriers, venue operations, and API integration — built on a single evidence architecture.",
    schemaType: "WebPage",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/Services", "/Consultation"],
  },

  // ─────────────────────────── MODULES ───────────────────────────
  "SecureQRStudio": {
    title: "Secure QR Studio | Structured Payloads & QR Workflows",
    description: "Generate and manage verifiable secure QR codes with permission binding and offline verification.",
    keywords: ["Secure QR Studio", "QR payload types", "QR code generator", "QR workflow", "identity QR", "ticket QR", "credential QR", "QR SDK"],
    h1: "Secure QR Studio with Structured Payload Types",
    url: "/SecureQRStudio",
    ogTitle: "Secure QR Studio | Structured Payloads & QR Workflows",
    ogDescription: "Generate and manage verifiable secure QR codes with permission binding and offline verification.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "daily",
    internalLinks: ["/ImageLab", "/Blockchain"],
  },
  "ImageLab": {
    title: "GlyphLock Image Lab | Carriers, Hotspots & QR Workflows",
    description: "Create images, test permitted LSB carriers, add responsive typed hotspots, connect Secure QR payloads, and retain provenance context in one workspace.",
    keywords: ["GlyphLock Image Lab", "image carrier", "LSB encoding", "interactive hotspots", "Secure QR", "image provenance", "typed actions"],
    h1: "GlyphLock Image Lab — Carriers, Hotspots and QR",
    url: "/ImageLab",
    ogTitle: "GlyphLock Image Lab | Carriers, Hotspots & QR Workflows",
    ogDescription: "Create images, test permitted LSB carriers, add responsive typed hotspots, connect Secure QR payloads, and retain provenance context in one workspace.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/InteractiveImageStudio"],
  },
  "InteractiveImageStudio": {
    title: "Interactive Image Studio | Responsive Hotspots & Actions",
    description: "Add normalized hotspot regions to images, attach typed links or text actions, preserve placement across screen sizes, and retain shareable image context.",
    keywords: ["interactive image studio", "responsive image hotspots", "normalized hotspot regions", "typed image actions", "image links", "shareable image context"],
    h1: "Interactive Images with Responsive Typed Hotspots",
    url: "/InteractiveImageStudio",
    ogTitle: "Interactive Image Studio | Responsive Hotspots & Actions",
    ogDescription: "Add normalized hotspot regions to images, attach typed links or text actions, preserve placement across screen sizes, and retain shareable image context.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/ImageLab", "/SecureQRStudio"],
  },
  "ImageGenerator": {
    title: "AI Image Generator | GlyphLock",
    description: "Generate visual assets, retain prompt and creation context, and route approved images into GlyphLock carrier, hotspot, QR, and record workflows.",
    keywords: ["AI image generation", "image creation context", "image carrier workflow", "interactive image", "Secure QR image", "visual asset record"],
    h1: "AI Image Generation with Recorded Context",
    url: "/ImageGenerator",
    ogTitle: "AI Image Generator | GlyphLock",
    ogDescription: "Generate visual assets, retain prompt and creation context, and route approved images into GlyphLock carrier, hotspot, QR, and record workflows.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/ImageLab", "/ContentGenerator"],
  },
  "GlyphBot": {
    title: "GlyphBot | Governed AI Assistant for Connected Workflows",
    description: "Use GlyphBot to build, inspect, explain, and audit connected GlyphLock workflows with explicit user direction, recorded context, and human review.",
    keywords: ["GlyphBot", "governed AI assistant", "workflow assistant", "AI audit support", "human review", "NUPS assistant", "GlyphLock AI"],
    h1: "GlyphBot: Assisted Intelligence with Human Control",
    url: "/GlyphBot",
    ogTitle: "GlyphBot | Governed AI Assistant for Connected Workflows",
    ogDescription: "Use GlyphBot to build, inspect, explain, and audit connected GlyphLock workflows with explicit user direction, recorded context, and human review.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "daily",
    internalLinks: ["/ContentGenerator", "/GlyphBotMixer"],
  },
  "GlyphBotMixer": {
    title: "DJ Pro Mixer & Fable Visual Engine | GlyphLock",
    description: "Automated DJ workflows and the Fable visual engine connected to GlyphLock operations, with audio analysis, playlist assistance, and synced visualization.",
    keywords: ["DJ Pro Mixer", "automated DJ", "Fable visual engine", "audio analysis", "playlist assistance", "venue audio", "GlyphLock mixer"],
    h1: "Automated DJ and Fable Visual Engine",
    url: "/GlyphBotMixer",
    ogTitle: "DJ Pro Mixer & Fable Visual Engine | GlyphLock",
    ogDescription: "Automated DJ workflows and the Fable visual engine connected to GlyphLock operations, with audio analysis, playlist assistance, and synced visualization.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/GlyphBot", "/NUPSLanding"],
  },
  "SecurityTools": {
    title: "Security Tools | QR, Hash & Record Verification | GlyphLock",
    description: "GlyphLock security tools for QR verification, hash generation, record anchoring references, and provenance context within supported workflows.",
    keywords: ["security tools", "QR verification", "hash generator", "record anchoring", "provenance reference", "GlyphLock"],
    h1: "Security Tools for Verification and Provenance",
    url: "/SecurityTools",
    ogTitle: "Security Tools | QR, Hash & Record Verification | GlyphLock",
    ogDescription: "GlyphLock security tools for QR verification, hash generation, record anchoring references, and provenance context within supported workflows.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/Blockchain"],
  },
  "SecurityOperationsCenter": {
    title: "Security Operations | Access, Activity & Audit Visibility",
    description: "Review access controls, activity visibility, audit events, alerting, and security-operations surfaces implemented across GlyphLock workflows.",
    keywords: ["security operations", "access controls", "activity visibility", "audit events", "alerting", "GlyphLock"],
    h1: "Security Operations and Audit Visibility",
    url: "/SecurityOperationsCenter",
    ogTitle: "Security Operations | Access, Activity & Audit Visibility",
    ogDescription: "Review access controls, activity visibility, audit events, alerting, and security-operations surfaces implemented across GlyphLock workflows.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/SecurityTools", "/GovernanceHub"],
  },
  "Blockchain": {
    title: "Record Anchoring & Provenance References | GlyphLock",
    description: "Create record references for digital assets, identity events, and documents using hashes, timestamps, source context, and supported anchoring workflows.",
    keywords: ["record anchoring", "provenance reference", "cryptographic hash", "timestamped record", "digital asset record", "audit reference"],
    h1: "Record Anchoring and Provenance References",
    url: "/Blockchain",
    ogTitle: "Record Anchoring & Provenance References | GlyphLock",
    ogDescription: "Create record references for digital assets, identity events, and documents using hashes, timestamps, source context, and supported anchoring workflows.",
    schemaType: "Service",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/GovernanceHub"],
  },

  // ─────────────────────────── NUPS / FINANCIAL ───────────────────────────
  "NUPSLanding": {
    title: "NUPS | Nexus Unified POS System for Venue Operations",
    description: "NUPS: venue operations software for check-in, floor status, VIP contracts, POS, and nightly settlement.",
    keywords: ["NUPS", "Nexus Unified POS System", "venue operations software", "guest check-in", "identity verification workflow", "digital contracts", "venue ledger", "reconciliation", "payout records"],
    h1: "NUPS Connected Venue Operations",
    url: "/NUPSLanding",
    ogTitle: "NUPS | Nexus Unified POS System for Venue Operations",
    ogDescription: "NUPS: venue operations software for check-in, floor status, VIP contracts, POS, and nightly settlement.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/Pricing", "/GlyphLockFinancial"],
  },
  "GlyphLockFinancial": {
    title: "GlyphLock Financial | Settlement, Payout & Record Workflows",
    description: "Connect authorized payment references, split rules, payout destinations, settlement status, reconciliation, and audit records across venue operations.",
    keywords: ["GlyphLock Financial", "settlement workflow", "payout records", "split rules", "reconciliation", "venue financial records"],
    h1: "Settlement, Payout and Financial Record Workflows",
    url: "/GlyphLockFinancial",
    ogTitle: "GlyphLock Financial | Settlement, Payout & Record Workflows",
    ogDescription: "Connect authorized payment references, split rules, payout destinations, settlement status, reconciliation, and audit records across venue operations.",
    schemaType: "Service",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/Consultation", "/SecurityDocs"],
  },

  // ─────────────────────────── RESOURCES ───────────────────────────
  "SecurityDocs": {
    title: "GlyphLock Documentation | SDK, API & Integration Guides",
    description: "Read technical guidance for GlyphLock SDKs, APIs, QR and image workflows, NUPS integration, authentication, records, and deployment boundaries.",
    keywords: ["GlyphLock documentation", "GlyphLock SDK", "GlyphLock API", "QR integration guide", "NUPS integration", "authentication guide", "deployment documentation"],
    h1: "GlyphLock SDK, API and Integration Documentation",
    url: "/SecurityDocs",
    ogTitle: "GlyphLock Documentation | SDK, API & Integration Guides",
    ogDescription: "Read technical guidance for GlyphLock SDKs, APIs, QR and image workflows, NUPS integration, authentication, records, and deployment boundaries.",
    schemaType: "TechArticle",
    priority: 0.7,
    changefreq: "weekly",
    internalLinks: ["/Roadmap", "/FAQ"],
  },
  "SDKDocs": {
    title: "SDK Documentation | GlyphLock Integration SDKs",
    description: "GlyphLock SDK documentation: authentication, QR generation and verification, webhooks, and error handling.",
    keywords: ["GlyphLock SDK", "SDK documentation", "QR SDK", "image SDK", "NUPS SDK", "integration SDK"],
    h1: "GlyphLock SDK Documentation",
    url: "/SDKDocs",
    ogTitle: "SDK Documentation | GlyphLock Integration SDKs",
    ogDescription: "GlyphLock SDK documentation: authentication, QR generation and verification, webhooks, and error handling.",
    schemaType: "TechArticle",
    priority: 0.7,
    changefreq: "weekly",
    internalLinks: ["/SecurityDocs", "/Roadmap"],
  },
  "Roadmap": {
    title: "Product Roadmap | GlyphLock LLC",
    description: "See shipped, active, hardening, and planned GlyphLock work across NUPS, QR, AI, image, governance, financial, integration, and security modules.",
    keywords: ["GlyphLock roadmap", "NUPS roadmap", "product development", "AI workflows", "QR verification", "operational software"],
    h1: "GlyphLock Product Roadmap",
    url: "/Roadmap",
    ogTitle: "Product Roadmap | GlyphLock LLC",
    ogDescription: "See shipped, active, hardening, and planned GlyphLock work across NUPS, QR, AI, image, governance, financial, integration, and security modules.",
    schemaType: "Schedule",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/About", "/Partners"],
  },
  "Partners": {
    title: "Partnerships | NUPS, APIs & Evidence | GlyphLock",
    description: "Evidence-led GlyphLock partnerships across NUPS, Oracle OHIP, Cloud Marketplace enrollment, Simphony intake, secure QR, APIs, hardware and more.",
    keywords: ["GlyphLock partnerships", "NUPS venue operations", "Oracle OHIP integration", "Oracle Cloud Marketplace", "Oracle Simphony integration", "evidence infrastructure", "secure QR", "API partnership", "hospitality technology"],
    h1: "Partnerships Built Around Verifiable Progress",
    url: "/Partners",
    ogTitle: "Partnerships | NUPS, APIs & Evidence | GlyphLock",
    ogDescription: "Evidence-led GlyphLock partnerships across NUPS, Oracle OHIP, Cloud Marketplace enrollment, Simphony intake, secure QR, APIs, hardware and more.",
    schemaType: "AboutPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/Consultation", "/TechnicalEvidence", "/CaseStudyOracleOHIP", "/Contact"],
  },
  "DreamTeam": {
    title: "GlyphLock Leadership | Carlo, Jacub & Collin",
    description: "Meet Carlo Rene Earl in product and venue operations, Jacub Lough in finance and strategy, and Collin Vanderginst in engineering and systems.",
    keywords: ["GlyphLock leadership", "Carlo Rene Earl", "Jacub Lough", "Collin Vanderginst", "technology leadership", "venue operations leadership", "financial strategy", "systems engineering", "evidence infrastructure"],
    h1: "Three Disciplines. Direct Responsibility.",
    url: "/DreamTeam",
    ogTitle: "GlyphLock Leadership | Carlo, Jacub & Collin",
    ogDescription: "Meet Carlo Rene Earl in product and venue operations, Jacub Lough in finance and strategy, and Collin Vanderginst in engineering and systems.",
    schemaType: "AboutPage",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/About", "/AboutCarlo", "/Partners"],
  },
  "FAQ": {
    title: "FAQ | GlyphLock Help & Common Questions",
    description: "Find answers about GlyphLock secure QR, image workflows, GlyphBot, NUPS venue operations, integrations, account access, and deployment planning.",
    keywords: ["GlyphLock FAQ", "help guide", "QR help", "image lab help", "GlyphBot help", "NUPS help", "account access"],
    h1: "Frequently Asked Questions",
    url: "/FAQ",
    ogTitle: "FAQ | GlyphLock Help & Common Questions",
    ogDescription: "Find answers about GlyphLock secure QR, image workflows, GlyphBot, NUPS venue operations, integrations, account access, and deployment planning.",
    schemaType: "FAQPage",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/SecurityDocs", "/Contact"],
  },

  // ─────────────────────────── GOVERNANCE ───────────────────────────
  "GovernanceHub": {
    title: "Governance Hub | Master Covenant | GlyphLock",
    description: "GlyphLock governance hub: the Master Covenant framework, review methodology, documentation, and public-claims boundaries for AI-assisted workflows.",
    keywords: ["Governance Hub", "Master Covenant", "AI governance framework", "governance research", "AI accountability", "GlyphLock"],
    h1: "Governance Hub and Accountability Architecture",
    url: "/GovernanceHub",
    ogTitle: "Governance Hub | Master Covenant | GlyphLock",
    ogDescription: "GlyphLock governance hub: the Master Covenant framework, review methodology, documentation, and public-claims boundaries for AI-assisted workflows.",
    schemaType: "WebPage",
    priority: 0.95,
    changefreq: "monthly",
    internalLinks: ["/MasterCovenant", "/TechnicalEvidence", "/About"],
  },
  "MasterCovenant": {
    title: "Master Covenant | Governance Framework | GlyphLock",
    description: "GlyphLock’s internal AI governance and drafting framework. External enforceability depends on applicable law, actual assent, and conventional agreements.",
    keywords: ["Master Covenant", "AI governance framework", "governance research", "AI accountability", "contract drafting", "GlyphLock"],
    h1: "The Master Covenant — AI Governance Framework",
    url: "/MasterCovenant",
    ogTitle: "Master Covenant | Governance Framework | GlyphLock",
    ogDescription: "GlyphLock’s internal AI governance and drafting framework. External enforceability depends on applicable law, actual assent, and conventional agreements.",
    schemaType: "Article",
    priority: 0.95,
    changefreq: "monthly",
    internalLinks: ["/TechnicalEvidence", "/ProvenanceMethodology", "/CaseStudyCovenantVictory", "/About"],
  },
  "TrustSecurity": {
    title: "Trust & Security | GlyphLock LLC",
    description: "How GlyphLock approaches trust and security across access, identity, records, audit, and deployment boundaries for connected evidence workflows.",
    keywords: ["trust and security", "access controls", "identity workflows", "audit", "deployment boundaries", "GlyphLock"],
    h1: "Trust and Security at GlyphLock",
    url: "/TrustSecurity",
    ogTitle: "Trust & Security | GlyphLock LLC",
    ogDescription: "How GlyphLock approaches trust and security across access, identity, records, audit, and deployment boundaries for connected evidence workflows.",
    schemaType: "WebPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/SecurityOperationsCenter", "/Privacy"],
  },
  "NISTChallenge": {
    title: "NIST Research Archive | GlyphLock Technical Record",
    description: "Review an archived GlyphLock technical research page kept for context. Current capabilities and claims appear on active product and architecture pages.",
    keywords: ["GlyphLock research archive", "NIST research", "technical record", "architecture history"],
    h1: "GlyphLock NIST Research Archive",
    url: "/NISTChallenge",
    ogTitle: "NIST Research Archive | GlyphLock Technical Record",
    ogDescription: "Review an archived GlyphLock technical research page kept for context. Current capabilities and claims appear on active product and architecture pages.",
    schemaType: "Article",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/TechnicalEvidence", "/MasterCovenant"],
  },

  // ─────────────────────────── TECHNICAL EVIDENCE ───────────────────────────
  "TechnicalEvidence": {
    title: "Technical Evidence | GlyphLock LLC",
    description: "Review independently verifiable integration evidence, reproducible preservation methods, product positioning, and clearly labeled internal analysis.",
    keywords: ["GlyphLock technical evidence", "Oracle OHIP evidence", "NUPS positioning", "evidence preservation", "internal enforceability review"],
    h1: "Technical Evidence",
    url: "/TechnicalEvidence",
    ogTitle: "Technical Evidence | GlyphLock LLC",
    ogDescription: "Review independently verifiable integration evidence, reproducible preservation methods, product positioning, and clearly labeled internal analysis.",
    schemaType: "CollectionPage",
    priority: 0.95,
    changefreq: "weekly",
    internalLinks: ["/CaseStudyOracleOHIP", "/CaseStudyNUPS", "/ProvenanceMethodology", "/CaseStudyCovenantVictory", "/MasterCovenant"],
  },
  "CaseStudyOracleOHIP": {
    title: "NUPS Oracle OHIP Integration Evidence | GlyphLock",
    description: "Review NUPS Oracle OHIP sandbox evidence, Cloud Marketplace program approval, and formal Simphony integration intake with production boundaries explicit.",
    keywords: ["Nexus Unified POS System", "Oracle OHIP integration", "Partner Sandbox", "Oracle Cloud Marketplace", "Oracle Simphony integration", "read-only validation", "OPERA Cloud configuration", "hospitality integration evidence"],
    h1: "NUPS Oracle OHIP Partner Sandbox Evidence",
    url: "/CaseStudyOracleOHIP",
    ogTitle: "NUPS Oracle OHIP Integration Evidence | GlyphLock",
    ogDescription: "Review NUPS Oracle OHIP sandbox evidence, Cloud Marketplace program approval, and formal Simphony integration intake with production boundaries explicit.",
    schemaType: "TechArticle",
    datePublished: "2026-08-24",
    dateModified: "2026-08-25",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/OracleOHIPMilestone", "/NUPSLanding", "/TechnicalEvidence", "/Privacy", "/Contact"],
  },
  "OracleOHIPMilestone": {
    title: "Oracle OHIP, Marketplace & Simphony Progress | GlyphLock",
    description: "GlyphLock NUPS validated Oracle OHIP sandbox response, activated Cloud Marketplace enrollment, and submitted Simphony integration intake for Oracle review.",
    keywords: ["Nexus Unified POS System", "Oracle OHIP", "Oracle Hospitality", "Oracle Cloud Marketplace", "Oracle Simphony integration", "Partner Sandbox", "OPN member", "hospitality technology", "read-only validation"],
    h1: "GlyphLock Advances NUPS Across Oracle OHIP, Marketplace and Simphony Tracks",
    url: "/OracleOHIPMilestone",
    ogTitle: "Oracle OHIP, Marketplace & Simphony Progress | GlyphLock",
    ogDescription: "GlyphLock NUPS validated Oracle OHIP sandbox response, activated Cloud Marketplace enrollment, and submitted Simphony integration intake for Oracle review.",
    schemaType: "NewsArticle",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/CaseStudyOracleOHIP", "/NUPSLanding", "/TechnicalEvidence", "/Contact", "/Privacy"],
  },
  "CaseStudyNUPS": {
    title: "NUPS Product Category and Positioning | GlyphLock",
    description: "How the Nexus Unified POS System differs from payment platforms through integration design and evidence packaging, with explicit biometric-data boundaries.",
    keywords: ["Nexus Unified POS System", "NUPS positioning", "evidence packaging", "payment platform comparison", "biometric data handling"],
    h1: "NUPS Product Category and Positioning",
    url: "/CaseStudyNUPS",
    ogTitle: "NUPS Product Category and Positioning | GlyphLock",
    ogDescription: "How the Nexus Unified POS System differs from payment platforms through integration design and evidence packaging, with explicit biometric-data boundaries.",
    schemaType: "TechArticle",
    datePublished: "2026-08-25",
    dateModified: "2026-08-25",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/TechnicalEvidence", "/NUPSLanding", "/Privacy", "/Contact"],
  },
  "ProvenanceMethodology": {
    title: "Evidence-Preservation Methodology | GlyphLock",
    description: "A provider-neutral, reproducible method for capturing model outputs, hashing, timestamping, and cross-referencing evidence records across systems.",
    keywords: ["evidence preservation", "provenance record", "hashing", "timestamping", "model output capture"],
    h1: "Provenance and Evidence-Preservation Methodology",
    url: "/ProvenanceMethodology",
    ogTitle: "Evidence-Preservation Methodology | GlyphLock",
    ogDescription: "A provider-neutral, reproducible method for capturing model outputs, hashing, timestamping, and cross-referencing evidence records across systems.",
    schemaType: "TechArticle",
    datePublished: "2026-08-25",
    dateModified: "2026-08-25",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/TechnicalEvidence", "/MasterCovenant", "/CaseStudyCovenantVictory"],
  },
  "CaseStudyCovenantVictory": {
    title: "Internal Enforceability Review: Master Covenant | GlyphLock",
    description: "Internal analysis of Master Covenant incorporation, liability, governance, and IP-notice theories. No litigation occurred; counsel has not reviewed it.",
    keywords: ["Master Covenant", "internal enforceability review", "AI governance research", "contract incorporation", "operator liability"],
    h1: "Internal Enforceability Review: Master Covenant",
    url: "/CaseStudyCovenantVictory",
    ogTitle: "Internal Enforceability Review: Master Covenant | GlyphLock",
    ogDescription: "Internal analysis of Master Covenant incorporation, liability, governance, and IP-notice theories. No litigation occurred; counsel has not reviewed it.",
    schemaType: "TechArticle",
    datePublished: "2026-08-25",
    dateModified: "2026-08-25",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/TechnicalEvidence", "/MasterCovenant", "/ProvenanceMethodology"],
  },

  "VideoUpload": {
    title: "Media Upload & QR Codes | GlyphLock",
    description: "Upload supported video, audio, and image files, receive shareable URLs, and create QR codes for approved media workflows within GlyphLock projects.",
    keywords: ["GlyphLock media upload", "shareable media URL", "media QR code", "video upload", "audio upload", "image upload"],
    h1: "Media Upload Hub",
    url: "/VideoUpload",
    ogTitle: "Media Upload & QR Codes | GlyphLock",
    ogDescription: "Upload supported video, audio, and image files, receive shareable URLs, and create QR codes for approved media workflows within GlyphLock projects.",
    schemaType: "SoftwareApplication",
    priority: 0.5,
    changefreq: "monthly",
    internalLinks: ["/SecureQRStudio", "/ImageLab"],
  },

  // ─────────────────────────── LEGAL ───────────────────────────
  "Privacy": {
    title: "Privacy Policy | Data Protection Standards | GlyphLock LLC",
    description: "Read how GlyphLock handles data collection, use, storage, sharing, retention, user choices, and privacy contacts across its services and workflows.",
    keywords: ["GlyphLock privacy policy", "data collection", "data use", "data retention", "privacy choices"],
    h1: "Privacy Policy & Data Protection Standards",
    url: "/Privacy",
    ogTitle: "Privacy Policy | Data Protection Standards | GlyphLock LLC",
    ogDescription: "Read how GlyphLock handles data collection, use, storage, sharing, retention, user choices, and privacy contacts across its services and workflows.",
    schemaType: "WebPage",
    priority: 0.5,
    changefreq: "yearly",
    internalLinks: ["/Terms", "/Contact"],
  },
  "Terms": {
    title: "Terms of Service | GlyphLock LLC",
    description: "Review the terms governing access to GlyphLock software, services, accounts, acceptable use, intellectual property, and related user responsibilities.",
    keywords: ["terms of service", "platform terms", "enterprise agreement"],
    h1: "Terms of Service",
    url: "/Terms",
    ogTitle: "Terms of Service | GlyphLock LLC",
    ogDescription: "Review the terms governing access to GlyphLock software, services, accounts, acceptable use, intellectual property, and related user responsibilities.",
    schemaType: "WebPage",
    priority: 0.5,
    changefreq: "yearly",
    internalLinks: ["/Privacy", "/Contact"],
  },
  "Cookies": {
    title: "Cookie Policy | GlyphLock LLC",
    description: "Learn how GlyphLock uses cookies and similar technologies, what they support, and what choices may be available when using its websites and services.",
    keywords: ["cookie policy", "cookies", "tracking technologies"],
    h1: "Cookie Policy",
    url: "/Cookies",
    ogTitle: "Cookie Policy | GlyphLock LLC",
    ogDescription: "Learn how GlyphLock uses cookies and similar technologies, what they support, and what choices may be available when using its websites and services.",
    schemaType: "WebPage",
    priority: 0.4,
    changefreq: "yearly",
    internalLinks: ["/Privacy", "/Terms"],
  },
  "Accessibility": {
    title: "Accessibility | GlyphLock LLC",
    description: "Read GlyphLock’s accessibility statement, supported accommodations, known limitations, and contact options for help using its websites and services.",
    keywords: ["accessibility", "a11y", "accommodations", "GlyphLock"],
    h1: "Accessibility at GlyphLock",
    url: "/Accessibility",
    ogTitle: "Accessibility | GlyphLock LLC",
    ogDescription: "Read GlyphLock’s accessibility statement, supported accommodations, known limitations, and contact options for help using its websites and services.",
    schemaType: "WebPage",
    priority: 0.4,
    changefreq: "yearly",
    internalLinks: ["/Contact", "/Privacy"],
  },
  "CodeOfEthics": {
    title: "Code of Ethics | GlyphLock LLC",
    description: "Review GlyphLock’s expectations for lawful conduct, accountability, evidence handling, human oversight, and responsible use of connected workflows.",
    keywords: ["code of ethics", "conduct", "accountability", "governance", "GlyphLock"],
    h1: "GlyphLock Code of Ethics",
    url: "/CodeOfEthics",
    ogTitle: "Code of Ethics | GlyphLock LLC",
    ogDescription: "Review GlyphLock’s expectations for lawful conduct, accountability, evidence handling, human oversight, and responsible use of connected workflows.",
    schemaType: "WebPage",
    priority: 0.6,
    changefreq: "yearly",
    internalLinks: ["/GovernanceHub", "/MasterCovenant"],
  },
};

export const isCanonicalPublicSeoPath = (path = "/") =>
  Object.values(SEO_DATA).some((entry) => entry.url === path);

export const getSeoData = (pageName) => {
  return SEO_DATA[pageName] || {
    title: "GlyphLock | Evidence Infrastructure for Identity & Proof",
    description: "Evidence infrastructure for identity, operations, and proof. Secure QR, verified access, and financial accountability in one auditable system.",
    keywords: [...GLOBAL_FALLBACK_KEYWORDS],
    h1: "GlyphLock Platform",
    positioningLine: CANONICAL_POSITIONING_LINE,
    url: "/",
    ogTitle: "GlyphLock | Evidence Infrastructure for Identity & Proof",
    ogDescription: "Evidence infrastructure for identity, operations, and proof. Secure QR, verified access, and financial accountability in one auditable system.",
    schemaType: "WebSite",
    priority: 0.5,
    internalLinks: [],
  };
};
