// ============================================================================
// seoData.jsx — CANONICAL RUNTIME SOURCE OF TRUTH for GlyphLock SEO metadata.
// ----------------------------------------------------------------------------
// Rules (enforced by scripts/check-seo-metadata.mjs):
//  - One entry per real public route. URLs use ACTUAL route casing from
//    pages.config.js / App.jsx (e.g. /SecureQRStudio, /ImageLab, /GlyphBot,
//    /NUPSLanding, /SDKDocs, /GlyphLockFinancial). No obsolete service slugs.
//  - No retired/misleading strings: "What If an Image Could Carry Proof?",
//    "Nexus Unified Portal System", "Dream Dollars", "banking-grade",
//    "Quantum-Grade"/"quantum-resistant", "revolutionary", "instant payout",
//    "automated processor split", "public-production API", patent claims,
//    "DACO¹", preview URLs, stale app IDs.
//  - NUPS expands to "Nexus Unified POS System" only.
//  - Structured data is claims-safe: no unsupported certification, endorsement,
//    price, rating, partner, patent, or production claims.
//  - Canonical origin: https://glyphlock.io
// ============================================================================

export const CANONICAL_ORIGIN = "https://glyphlock.io";

// Global fallback keyword set — also used for the Home page.
export const GLOBAL_FALLBACK_KEYWORDS = [
  "GlyphLock",
  "evidence infrastructure",
  "identity and permission workflows",
  "Secure QR",
  "interactive images",
  "GlyphBot",
  "automated DJ",
  "NUPS",
  "venue operations software",
  "financial accountability",
  "API and SDK integration",
  "governance",
];

export const SEO_DATA = {
  // ─────────────────────────── CORE PAGES ───────────────────────────
  "Home": {
    title: "GlyphLock | Evidence Infrastructure for Identity, Operations & Proof",
    description: "GlyphLock connects identity and permission, secure QR and image carriers, AI-assisted workflows, NUPS venue operations, financial accountability, APIs, hardware, and governance through one evidence architecture.",
    keywords: [...GLOBAL_FALLBACK_KEYWORDS],
    h1: "Build. Verify. Operate.",
    url: "/",
    ogTitle: "GlyphLock | Connected Evidence Infrastructure",
    ogDescription: "From Secure QR and interactive media to automated DJ, NUPS, financial records, SDKs, APIs, hardware, and governance—GlyphLock connects the full operating event.",
    schemaType: "Organization",
    priority: 1.0,
    changefreq: "daily",
    internalLinks: ["/About", "/SecureQRStudio", "/GlyphBot", "/NUPSLanding", "/Services", "/Consultation"],
  },
  "About": {
    title: "About GlyphLock | Technology, NUPS & Evidence Architecture",
    description: "See how GlyphLock connects identity, secure QR, image carriers, GlyphBot, automated DJ and Fable, NUPS venue operations, GlyphBucks accounting, SDKs, APIs, hardware, OHIP integration work, and governance.",
    keywords: [
      "GlyphLock", "evidence infrastructure", "identity and permission workflows", "Secure QR Studio",
      "QR verification", "interactive images", "image carrier research", "GlyphBot", "automated DJ software",
      "Fable visual engine", "NUPS", "Nexus Unified POS System", "venue operations software", "digital contracts",
      "GlyphBucks", "closed-loop stored value", "reconciliation", "API integration", "SDK integration", "webhooks",
      "hardware integration", "Oracle Hospitality integration", "OHIP integration work", "audit trails", "governance",
      "Carlo Rene Earl", "Jacub Lough", "Collin Vanderginst", "El Mirage Arizona",
    ],
    h1: "Identity. Permission. Operations. Proof.",
    url: "/About",
    ogTitle: "About GlyphLock | One Core, Six Domains, One Trust Envelope",
    ogDescription: "Explore GlyphLock’s evidence core, six operating domains, trust envelope, technical systems, operating proof, leadership, and integration surfaces.",
    schemaType: "AboutPage",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/ImageLab", "/InteractiveImageStudio", "/GlyphBot", "/GlyphBotMixer", "/NUPSLanding", "/GlyphLockFinancial", "/GovernanceHub", "/SecurityOperationsCenter", "/SDKDocs", "/AboutCarlo", "/Consultation"],
  },
  "AboutCarlo": {
    title: "Carlo René Earl | GlyphLock Founder & NUPS Creator",
    description: "Carlo René Earl built GlyphLock and NUPS (Nexus Unified POS System) from venue experience, connecting identity, operations, agreements, transaction evidence, and audit history.",
    keywords: ["Carlo René Earl", "Carlo Rene Earl", "GlyphLock founder", "NUPS creator", "GlyphLock product architect", "venue operations founder", "hospitality technology", "transaction evidence", "identity workflows", "Arizona technology founder"],
    h1: "This Is Not a Resume",
    url: "/AboutCarlo",
    ogTitle: "The Founder Story Behind GlyphLock and NUPS",
    ogDescription: "From nightlife operations and a concealed-image experiment to a live venue platform and an Oracle integration path: the documented story behind GlyphLock.",
    schemaType: "ProfilePage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/About", "/Partners", "/Contact", "/Consultation"],
  },
  "Pricing": {
    title: "GlyphLock Plans | Evidence Infrastructure & NUPS",
    description: "Compare access options for GlyphLock image-carrier tools, Secure QR workflows, GlyphBot assistance, NUPS operations, integrations, and governance resources.",
    keywords: ["GlyphLock pricing", "evidence infrastructure plans", "Secure QR plans", "NUPS access", "GlyphBot access", "venue operations software"],
    h1: "Plans for Connected Evidence and Operations",
    url: "/Pricing",
    ogTitle: "GlyphLock Plans | Evidence Infrastructure & NUPS",
    ogDescription: "Compare GlyphLock access options across secure carriers, assisted intelligence, venue operations, integrations, and governance.",
    schemaType: "PricingTable",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/Consultation", "/Services"],
  },
  "Contact": {
    title: "Contact GlyphLock | Product & Deployment Consultation",
    description: "Contact GlyphLock about secure image carriers, QR workflows, GlyphBot, NUPS venue operations, financial records, SDKs, APIs, and authorized integrations.",
    keywords: ["contact GlyphLock", "GlyphLock consultation", "NUPS deployment", "Secure QR integration", "GlyphBot", "API integration"],
    h1: "Discuss a GlyphLock Deployment",
    url: "/Contact",
    ogTitle: "Contact GlyphLock | Product & Deployment Consultation",
    ogDescription: "Discuss carriers, QR, AI assistance, NUPS operations, value records, SDKs, APIs, and integrations with GlyphLock.",
    schemaType: "ContactPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/FAQ", "/Consultation"],
  },
  "Consultation": {
    title: "GlyphLock Architecture Consultation | Plan a Deployment",
    description: "Map a GlyphLock deployment across image carriers, Secure QR, GlyphBot, NUPS, identity and contract workflows, ledgers, SDKs, APIs, and integrations.",
    keywords: ["GlyphLock architecture consultation", "NUPS deployment planning", "Secure QR workflow", "SDK integration", "API integration", "venue systems"],
    h1: "Plan a Connected GlyphLock Deployment",
    url: "/Consultation",
    ogTitle: "GlyphLock Architecture Consultation",
    ogDescription: "Plan how GlyphLock carriers, intelligence, operations, value records, integrations, and governance fit your workflow.",
    schemaType: "Service",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/Pricing", "/Services"],
  },
  "Services": {
    title: "GlyphLock Services | Custom Software, Integration & Operations",
    description: "GlyphLock services span custom software, system integration, AI engineering, operations software, and deployment support for connected evidence workflows.",
    keywords: ["GlyphLock services", "custom software", "system integration", "AI engineering", "operations software", "deployment support"],
    h1: "Services for Connected Evidence and Operations",
    url: "/Services",
    ogTitle: "GlyphLock Services | Custom Software & Integration",
    ogDescription: "Custom software, integration, AI engineering, and operations software for connected evidence workflows.",
    schemaType: "Service",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/Consultation", "/Solutions"],
  },
  "Solutions": {
    title: "GlyphLock Solutions | Identity, Operations & Proof Workflows",
    description: "Explore GlyphLock solution patterns across identity and permission, secure QR, interactive media, AI assistance, NUPS operations, financial records, and governance.",
    keywords: ["GlyphLock solutions", "identity workflows", "Secure QR", "interactive images", "NUPS operations", "financial records", "governance"],
    h1: "Solution Patterns for Connected Workflows",
    url: "/Solutions",
    ogTitle: "GlyphLock Solutions | Identity, Operations & Proof",
    ogDescription: "Solution patterns across identity, secure QR, media, AI assistance, NUPS, financial records, and governance.",
    schemaType: "WebPage",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/Services", "/Consultation"],
  },

  // ─────────────────────────── MODULES ───────────────────────────
  "SecureQRStudio": {
    title: "Secure QR Studio | Structured Payloads & QR Workflows",
    description: "Create and manage QR carriers from a structured payload catalog covering links, identity, tickets, credentials, records, actions, and operational references.",
    keywords: ["Secure QR Studio", "QR payload types", "QR code generator", "QR workflow", "identity QR", "ticket QR", "credential QR", "QR SDK"],
    h1: "Secure QR Studio with Structured Payload Types",
    url: "/SecureQRStudio",
    ogTitle: "Secure QR Studio | GlyphLock",
    ogDescription: "Build QR carriers for links, identity, tickets, credentials, records, actions, and connected operational workflows.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "daily",
    internalLinks: ["/ImageLab", "/Blockchain"],
  },
  "ImageLab": {
    title: "GlyphLock Image Lab | Carriers, Hotspots & QR Workflows",
    description: "Create images, test permitted LSB carriers, add responsive typed hotspots, connect Secure QR payloads, and retain provenance context in one workspace.",
    keywords: ["GlyphLock Image Lab", "image carrier", "LSB encoding", "interactive hotspots", "Secure QR", "image provenance", "typed actions"],
    h1: "GlyphLock Image Lab — Carriers, Hotspots and QR",
    url: "/ImageLab",
    ogTitle: "GlyphLock Image Lab | Carriers, Hotspots & QR",
    ogDescription: "Connect image creation, LSB carrier tests, responsive hotspots, Secure QR payloads, and recorded context.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/InteractiveImageStudio"],
  },
  "InteractiveImageStudio": {
    title: "Interactive Image Studio | Responsive Hotspots & Actions",
    description: "Add normalized hotspot regions to images, attach typed links or text actions, preserve placement across screen sizes, and retain shareable image context.",
    keywords: ["interactive image studio", "responsive image hotspots", "normalized hotspot regions", "typed image actions", "image links", "shareable image context"],
    h1: "Interactive Images with Responsive Typed Hotspots",
    url: "/InteractiveImageStudio",
    ogTitle: "Interactive Image Studio | GlyphLock",
    ogDescription: "Add responsive hotspot regions, typed links or text actions, and shareable context to an image.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/ImageLab", "/SecureQRStudio"],
  },
  "ImageGenerator": {
    title: "AI Image Generator | GlyphLock",
    description: "Generate visual assets, retain prompt and creation context, and route approved images into GlyphLock carrier, hotspot, QR, and record workflows.",
    keywords: ["AI image generation", "image creation context", "image carrier workflow", "interactive image", "Secure QR image", "visual asset record"],
    h1: "AI Image Generation with Recorded Context",
    url: "/ImageGenerator",
    ogTitle: "AI Image Generation | GlyphLock LLC",
    ogDescription: "Generate images with retained creation context for carrier, hotspot, QR, and connected record workflows.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/ImageLab", "/ContentGenerator"],
  },
  "GlyphBot": {
    title: "GlyphBot | Governed AI Assistant for Connected Workflows",
    description: "Use GlyphBot to build, inspect, explain, and audit connected GlyphLock workflows with explicit user direction, recorded context, and human review.",
    keywords: ["GlyphBot", "governed AI assistant", "workflow assistant", "AI audit support", "human review", "NUPS assistant", "GlyphLock AI"],
    h1: "GlyphBot: Assisted Intelligence with Human Control",
    url: "/GlyphBot",
    ogTitle: "GlyphBot | Governed AI Assistant",
    ogDescription: "Build, inspect, explain, and audit connected workflows with explicit user direction and human review.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "daily",
    internalLinks: ["/ContentGenerator", "/GlyphBotMixer"],
  },
  "GlyphBotMixer": {
    title: "DJ Pro Mixer & Fable Visual Engine | GlyphLock",
    description: "Automated DJ workflows and the Fable visual engine connected to GlyphLock operations, with audio analysis, playlist assistance, and synced visualization.",
    keywords: ["DJ Pro Mixer", "automated DJ", "Fable visual engine", "audio analysis", "playlist assistance", "venue audio", "GlyphLock mixer"],
    h1: "Automated DJ and Fable Visual Engine",
    url: "/GlyphBotMixer",
    ogTitle: "DJ Pro Mixer & Fable Visual Engine | GlyphLock",
    ogDescription: "Automated DJ workflows and the Fable visual engine connected to GlyphLock operations.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/GlyphBot", "/NUPSLanding"],
  },
  "SecurityTools": {
    title: "Security Tools | QR, Hash & Record Verification | GlyphLock",
    description: "GlyphLock security tools for QR verification, hash generation, record anchoring references, and provenance context within supported workflows.",
    keywords: ["security tools", "QR verification", "hash generator", "record anchoring", "provenance reference", "GlyphLock"],
    h1: "Security Tools for Verification and Provenance",
    url: "/SecurityTools",
    ogTitle: "Security Tools | GlyphLock",
    ogDescription: "QR verification, hash generation, record anchoring references, and provenance context.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/Blockchain"],
  },
  "SecurityOperationsCenter": {
    title: "Security Operations | Access, Activity & Audit Visibility",
    description: "Review access controls, activity visibility, audit events, alerting, and security-operations surfaces implemented across GlyphLock workflows.",
    keywords: ["security operations", "access controls", "activity visibility", "audit events", "alerting", "GlyphLock"],
    h1: "Security Operations and Audit Visibility",
    url: "/SecurityOperationsCenter",
    ogTitle: "Security Operations | GlyphLock",
    ogDescription: "Access controls, activity visibility, audit events, alerting, and security operations tooling.",
    schemaType: "SoftwareApplication",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/SecurityTools", "/GovernanceHub"],
  },
  "Blockchain": {
    title: "Record Anchoring & Provenance References | GlyphLock",
    description: "Create record references for digital assets, identity events, and documents using hashes, timestamps, source context, and supported anchoring workflows.",
    keywords: ["record anchoring", "provenance reference", "cryptographic hash", "timestamped record", "digital asset record", "audit reference"],
    h1: "Record Anchoring and Provenance References",
    url: "/Blockchain",
    ogTitle: "Record Anchoring & Provenance References | GlyphLock",
    ogDescription: "Record references, hashes, and provenance context for digital assets, identity records, and documentation.",
    schemaType: "Service",
    priority: 0.8,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/GovernanceHub"],
  },

  // ─────────────────────────── NUPS / FINANCIAL ───────────────────────────
  "NUPSLanding": {
    title: "NUPS | Nexus Unified POS System for Venue Operations",
    description: "NUPS (Nexus Unified POS System) connects venue context, identity, roles, agreements, sales and service references, batches, reconciliation, payouts, and audit history.",
    keywords: ["NUPS", "Nexus Unified POS System", "venue operations software", "guest check-in", "identity verification workflow", "digital contracts", "venue ledger", "reconciliation", "payout records"],
    h1: "NUPS Connected Venue Operations",
    url: "/NUPSLanding",
    ogTitle: "NUPS | Connected Venue Operations",
    ogDescription: "Connect identity, roles, agreements, venue activity, transaction references, batches, reconciliation, payouts, and audit history.",
    schemaType: "SoftwareApplication",
    priority: 0.9,
    changefreq: "weekly",
    internalLinks: ["/SecureQRStudio", "/Pricing", "/GlyphLockFinancial"],
  },
  "GlyphLockFinancial": {
    title: "GlyphLock Financial | Settlement, Payout & Record Workflows",
    description: "Connect authorized payment references, split rules, payout destinations, settlement status, reconciliation, and audit records across venue operations.",
    keywords: ["GlyphLock Financial", "settlement workflow", "payout records", "split rules", "reconciliation", "venue financial records"],
    h1: "Settlement, Payout and Financial Record Workflows",
    url: "/GlyphLockFinancial",
    ogTitle: "GlyphLock Financial | GlyphLock LLC",
    ogDescription: "Connect authorized payment references, split rules, settlement status, payout destinations, reconciliation, and audit records.",
    schemaType: "Service",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/Consultation", "/SecurityDocs"],
  },

  // ─────────────────────────── RESOURCES ───────────────────────────
  "SecurityDocs": {
    title: "GlyphLock Documentation | SDK, API & Integration Guides",
    description: "Read technical guidance for GlyphLock SDKs, APIs, QR and image workflows, NUPS integration, authentication, records, and deployment boundaries.",
    keywords: ["GlyphLock documentation", "GlyphLock SDK", "GlyphLock API", "QR integration guide", "NUPS integration", "authentication guide", "deployment documentation"],
    h1: "GlyphLock SDK, API and Integration Documentation",
    url: "/SecurityDocs",
    ogTitle: "GlyphLock Documentation | SDK, API & Integrations",
    ogDescription: "Technical guidance for SDKs, APIs, QR, images, NUPS, authentication, records, and deployment boundaries.",
    schemaType: "TechArticle",
    priority: 0.7,
    changefreq: "weekly",
    internalLinks: ["/Roadmap", "/FAQ"],
  },
  "SDKDocs": {
    title: "SDK Documentation | GlyphLock Integration SDKs",
    description: "Technical reference for GlyphLock SDKs covering QR, image, record, and NUPS integration with authentication and deployment boundaries.",
    keywords: ["GlyphLock SDK", "SDK documentation", "QR SDK", "image SDK", "NUPS SDK", "integration SDK"],
    h1: "GlyphLock SDK Documentation",
    url: "/SDKDocs",
    ogTitle: "SDK Documentation | GlyphLock",
    ogDescription: "Technical reference for GlyphLock SDKs across QR, image, record, and NUPS integration.",
    schemaType: "TechArticle",
    priority: 0.7,
    changefreq: "weekly",
    internalLinks: ["/SecurityDocs", "/Roadmap"],
  },
  "Roadmap": {
    title: "Product Roadmap | GlyphLock LLC",
    description: "See shipped, active, hardening, and planned GlyphLock work across NUPS, QR, AI, image, governance, financial, integration, and security modules.",
    keywords: ["GlyphLock roadmap", "NUPS roadmap", "product development", "AI workflows", "QR verification", "operational software"],
    h1: "GlyphLock Product Roadmap",
    url: "/Roadmap",
    ogTitle: "Product Roadmap | GlyphLock LLC",
    ogDescription: "Shipped, active, hardening, and planned work across the GlyphLock platform.",
    schemaType: "Schedule",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/About", "/Partners"],
  },
  "Partners": {
    title: "GlyphLock Partners | NUPS, QR, API & Hospitality",
    description: "Explore GlyphLock partnership and integration opportunities across image carriers, NUPS operations, SDK and API connections, hardware, and hospitality systems.",
    keywords: ["GlyphLock partners", "NUPS integration", "hospitality integration", "QR SDK", "API partnership", "venue technology", "hardware integration"],
    h1: "Partnership and Integration Opportunities",
    url: "/Partners",
    ogTitle: "GlyphLock Partners & Integration Opportunities",
    ogDescription: "Connect GlyphLock carriers, venue operations, SDKs, APIs, hardware, and hospitality workflows.",
    schemaType: "AboutPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/Contact", "/DreamTeam"],
  },
  "DreamTeam": {
    title: "GlyphLock Leadership | Carlo, Jacub & Collin",
    description: "Meet Carlo Rene Earl in product and venue operations, Jacub Lough in finance and strategy, and Collin Vanderginst in engineering and systems.",
    keywords: ["GlyphLock leadership", "Carlo Rene Earl", "Jacub Lough", "Collin Vanderginst", "technology leadership", "venue operations leadership", "financial strategy", "systems engineering", "evidence infrastructure"],
    h1: "Three Disciplines. Direct Responsibility.",
    url: "/DreamTeam",
    ogTitle: "Meet the GlyphLock Leadership Team",
    ogDescription: "Product and venue operations, finance and commercial strategy, and systems engineering united behind GlyphLock’s evidence infrastructure.",
    schemaType: "AboutPage",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/About", "/AboutCarlo", "/Partners"],
  },
  "FAQ": {
    title: "FAQ | GlyphLock Help & Common Questions",
    description: "Answers to common GlyphLock questions across QR, image, GlyphBot, NUPS venue operations, financial records, SDKs, APIs, and account access.",
    keywords: ["GlyphLock FAQ", "help guide", "QR help", "image lab help", "GlyphBot help", "NUPS help", "account access"],
    h1: "Frequently Asked Questions",
    url: "/FAQ",
    ogTitle: "FAQ | GlyphLock",
    ogDescription: "Common questions across QR, image, GlyphBot, NUPS, financial records, SDKs, APIs, and account access.",
    schemaType: "FAQPage",
    priority: 0.7,
    changefreq: "monthly",
    internalLinks: ["/SecurityDocs", "/Contact"],
  },

  // ─────────────────────────── GOVERNANCE ───────────────────────────
  "GovernanceHub": {
    title: "Governance Hub | Master Covenant & Accountability | GlyphLock",
    description: "GlyphLock governance hub: the Master Covenant framework, review methodology, documentation, and public-claims boundaries for AI-assisted workflows.",
    keywords: ["Governance Hub", "Master Covenant", "AI governance framework", "governance research", "AI accountability", "GlyphLock"],
    h1: "Governance Hub and Accountability Architecture",
    url: "/GovernanceHub",
    ogTitle: "Governance Hub | GlyphLock LLC",
    ogDescription: "Master Covenant governance, operating standards, documentation, and accountability architecture.",
    schemaType: "WebPage",
    priority: 0.95,
    changefreq: "monthly",
    internalLinks: ["/MasterCovenant", "/CaseStudies", "/About"],
  },
  "MasterCovenant": {
    title: "Master Covenant | Governance Framework | GlyphLock",
    description: "GlyphLock’s internal AI governance and drafting framework. External enforceability depends on applicable law, actual assent, and conventional agreements.",
    keywords: ["Master Covenant", "AI governance framework", "governance research", "AI accountability", "contract drafting", "GlyphLock"],
    h1: "The Master Covenant — AI Governance Framework",
    url: "/MasterCovenant",
    ogTitle: "Master Covenant | AI Governance Framework | GlyphLock LLC",
    ogDescription: "GlyphLock's internal governance and drafting framework for AI accountability concepts.",
    schemaType: "Article",
    priority: 0.95,
    changefreq: "monthly",
    internalLinks: ["/CaseStudies", "/CaseStudyAIBinding", "/CaseStudyCovenantVictory", "/About"],
  },
  "TrustSecurity": {
    title: "Trust & Security | GlyphLock LLC",
    description: "How GlyphLock approaches trust and security across access, identity, records, audit, and deployment boundaries for connected evidence workflows.",
    keywords: ["trust and security", "access controls", "identity workflows", "audit", "deployment boundaries", "GlyphLock"],
    h1: "Trust and Security at GlyphLock",
    url: "/TrustSecurity",
    ogTitle: "Trust & Security | GlyphLock LLC",
    ogDescription: "Access, identity, records, audit, and deployment boundaries for connected evidence workflows.",
    schemaType: "WebPage",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/SecurityOperationsCenter", "/Privacy"],
  },
  "NISTChallenge": {
    title: "NIST Research Archive | GlyphLock Technical Record",
    description: "Review an archived GlyphLock technical research page kept for context. Current capabilities and claims appear on active product and architecture pages.",
    keywords: ["GlyphLock research archive", "NIST research", "technical record", "architecture history"],
    h1: "GlyphLock NIST Research Archive",
    url: "/NISTChallenge",
    ogTitle: "NIST Research Archive | GlyphLock",
    ogDescription: "An archived technical research page retained for historical context, with current claims documented elsewhere.",
    schemaType: "Article",
    priority: 0.8,
    changefreq: "monthly",
    internalLinks: ["/CaseStudies", "/MasterCovenant"],
  },

  // ─────────────────────────── CASE STUDIES ───────────────────────────
  "CaseStudies": {
    title: "Case Studies & Research | GlyphLock LLC",
    description: "Explore GlyphLock internal research, reported incidents, archived outputs, simulations, operational software work, and separately identified validation.",
    keywords: ["GlyphLock case studies", "AI governance research", "Master Covenant", "incident documentation", "operational software", "archived system outputs"],
    h1: "Case Studies & Security Research",
    url: "/CaseStudies",
    ogTitle: "Case Studies & Research | GlyphLock LLC",
    ogDescription: "Internal research, reported incidents, archived outputs, simulations, and operational case studies from GlyphLock.",
    schemaType: "CollectionPage",
    priority: 0.95,
    changefreq: "weekly",
    internalLinks: ["/CaseStudyTruthStrike", "/CaseStudyAIBinding", "/CaseStudyCovenantVictory", "/MasterCovenant"],
  },
  "CaseStudyTruthStrike": {
    title: "TruthStrike Incident Record | GlyphLock LLC",
    description: "Review reported events, archived evidence, internal PROBE classifications, and a reported IC3 complaint. Filing does not establish agency validation.",
    keywords: ["TruthStrike incident record", "incident documentation", "archived evidence", "PROBE classification", "reported IC3 complaint"],
    h1: "TruthStrike Incident Documentation",
    url: "/CaseStudyTruthStrike",
    ogTitle: "TruthStrike Incident | GlyphLock LLC",
    ogDescription: "Reported incident documentation, internal classifications, archived evidence, and a reported IC3 complaint submission.",
    schemaType: "Article",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/CaseStudies", "/MasterCovenant", "/CaseStudyAIBinding"],
  },
  "CaseStudyAIBinding": {
    title: "AI Governance Case Study | Master Covenant | GlyphLock",
    description: "Internal study of AI-system outputs classified under GlyphLock’s Master Covenant. It does not claim contractual assent by any AI provider.",
    keywords: ["AI governance", "AI workflow records", "Master Covenant", "AI governance framework", "GlyphLock research"],
    h1: "AI Governance Acknowledgments Under the Master Covenant",
    url: "/CaseStudyAIBinding",
    ogTitle: "AI Governance Acknowledgment Case Study | GlyphLock LLC",
    ogDescription: "Internal governance case study documenting AI-system acknowledgments and provenance artifacts under the Master Covenant framework.",
    schemaType: "Article",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/CaseStudies", "/MasterCovenant", "/CaseStudyCovenantVictory"],
  },
  "CaseStudyCovenantVictory": {
    title: "Master Covenant Litigation Simulation | GlyphLock",
    description: "Internal simulation evaluating Master Covenant governance, operator liability, contract incorporation, and IP-notice theories. Not a court ruling.",
    keywords: ["Master Covenant", "litigation simulation", "AI governance research", "IP notice", "operator liability"],
    h1: "Master Covenant Litigation Simulation",
    url: "/CaseStudyCovenantVictory",
    ogTitle: "Master Covenant Litigation Simulation | GlyphLock LLC",
    ogDescription: "Internal simulation research evaluating Master Covenant governance and enforceability theories; not judicial validation.",
    schemaType: "Article",
    priority: 0.9,
    changefreq: "monthly",
    internalLinks: ["/CaseStudies", "/MasterCovenant", "/CaseStudyAIBinding"],
  },

  // ─────────────────────────── LEGAL ───────────────────────────
  "Privacy": {
    title: "Privacy Policy | Data Protection Standards | GlyphLock LLC",
    description: "Read how GlyphLock describes data collection, use, storage, sharing, retention, user choices, and contact options for its services.",
    keywords: ["GlyphLock privacy policy", "data collection", "data use", "data retention", "privacy choices"],
    h1: "Privacy Policy & Data Protection Standards",
    url: "/Privacy",
    ogTitle: "Privacy Policy | GlyphLock LLC",
    ogDescription: "Data protection standards and privacy choices for GlyphLock services.",
    schemaType: "WebPage",
    priority: 0.5,
    changefreq: "yearly",
    internalLinks: ["/Terms", "/Contact"],
  },
  "Terms": {
    title: "Terms of Service | GlyphLock LLC",
    description: "Terms and conditions for the GlyphLock platform and services.",
    keywords: ["terms of service", "platform terms", "enterprise agreement"],
    h1: "Terms of Service",
    url: "/Terms",
    ogTitle: "Terms of Service | GlyphLock LLC",
    ogDescription: "Platform terms and service agreements for GlyphLock.",
    schemaType: "WebPage",
    priority: 0.5,
    changefreq: "yearly",
    internalLinks: ["/Privacy", "/Contact"],
  },
  "Cookies": {
    title: "Cookie Policy | GlyphLock LLC",
    description: "How GlyphLock uses cookies and similar technologies across its services.",
    keywords: ["cookie policy", "cookies", "tracking technologies"],
    h1: "Cookie Policy",
    url: "/Cookies",
    ogTitle: "Cookie Policy | GlyphLock LLC",
    ogDescription: "How GlyphLock uses cookies and similar technologies.",
    schemaType: "WebPage",
    priority: 0.4,
    changefreq: "yearly",
    internalLinks: ["/Privacy", "/Terms"],
  },
  "Accessibility": {
    title: "Accessibility | GlyphLock LLC",
    description: "GlyphLock accessibility statement and available accommodations for users across its services.",
    keywords: ["accessibility", "a11y", "accommodations", "GlyphLock"],
    h1: "Accessibility at GlyphLock",
    url: "/Accessibility",
    ogTitle: "Accessibility | GlyphLock LLC",
    ogDescription: "Accessibility statement and available accommodations for GlyphLock services.",
    schemaType: "WebPage",
    priority: 0.4,
    changefreq: "yearly",
    internalLinks: ["/Contact", "/Privacy"],
  },
  "CodeOfEthics": {
    title: "Code of Ethics | GlyphLock LLC",
    description: "GlyphLock code of ethics covering conduct, accountability, and governance for connected evidence workflows.",
    keywords: ["code of ethics", "conduct", "accountability", "governance", "GlyphLock"],
    h1: "GlyphLock Code of Ethics",
    url: "/CodeOfEthics",
    ogTitle: "Code of Ethics | GlyphLock LLC",
    ogDescription: "Conduct, accountability, and governance for connected evidence workflows.",
    schemaType: "WebPage",
    priority: 0.6,
    changefreq: "yearly",
    internalLinks: ["/GovernanceHub", "/MasterCovenant"],
  },
};

export const getSeoData = (pageName) => {
  return SEO_DATA[pageName] || {
    title: "GlyphLock | Evidence Infrastructure for Identity, Operations & Proof",
    description: "GlyphLock connects identity and permission, secure QR and image carriers, AI-assisted workflows, NUPS venue operations, financial accountability, APIs, hardware, and governance through one evidence architecture.",
    keywords: [...GLOBAL_FALLBACK_KEYWORDS],
    h1: "GlyphLock Platform",
    url: "/",
    ogTitle: "GlyphLock | Connected Evidence Infrastructure",
    ogDescription: "From Secure QR and interactive media to automated DJ, NUPS, financial records, SDKs, APIs, hardware, and governance—GlyphLock connects the full operating event.",
    schemaType: "WebSite",
    priority: 0.5,
    internalLinks: [],
  };
};