const SITE_URL = 'https://glyphlock.io';

const USER_AGENTS = [
  "Googlebot",
  "Bingbot",
  "GPTBot",
  "ClaudeBot",
  "anthropic-ai",
  "PerplexityBot",
  "Google-Extended",
  "Applebot-Extended",
  "CCBot",
  "*"
];
const PRIVATE_ROUTES = [
  "/Dashboard",
  "/CommandCenter",
  "/ProjectUpdates",
  "/AccountSecurity",
  "/BillingAndPayments",
  "/ManageSubscription",
  "/PaymentSuccess",
  "/PaymentCancel",
  "/ConsultationSuccess",
  "/EmergencyBackup",
  "/FullExport",
  "/GlyphLockAudit",
  "/GlyphLockPlayground",
  "/IntegrationTests",
  "/SystemAudit",
  "/SettlementReports",
  "/AnalyticsDashboard",
  "/NUPSDemoManager",
  "/NUPSOwner",
  "/NUPSPostLogin",
  "/NUPSReport",
  "/NUPSSandbox",
  "/NUPSStaff",
  "/NUPSAudit",
  "/NUPSInfrastructurePage",
  "/SiteBuilder",
  "/SiteBuilderTest",
  "/SiteAudit",
  "/Sie",
  "/ClubCurrencyPress",
  "/ContractArchive",
  "/ContractSearch",
  "/StrategicScale",
  "/OHIPReadiness",
  "/VIPContract",
  "/Sitemap",
  "/SitemapApp",
  "/SitemapDynamic",
  "/SitemapImages",
  "/SitemapInteractive",
  "/SitemapQr",
  "/sitemap-qr",
  "/Robots",
  "/NotFound",
  "/api/",
  "/functions/",
  "/admin/",
  "/demo/",
  "/unauthorized",
  "/ProviderConsole",
  "/providerconsole",
  "/NUPSAdminPortal",
  "/nupsadminportal",
  "/nupskiosk",
  "/nupshub",
  "/register",
  "/registerconsole",
  "/barregister",
  "/receipts",
  "/driverpayouts",
  "/glyphbucks",
  "/accounting",
  "/tonight",
  "/contracts",
  "/contractshub",
  "/vipbillprinter",
  "/managerconsole",
  "/peoplearchive",
  "/ledgertrialbalance",
  "/frontdoor",
  "/entertainercheckin",
  "/djhome",
  "/vipsale",
  "/vipcommand",
  "/vipshowcontracts",
  "/v/",
  "/offlineverify",
  "/mobilescanner",
  "/clubtv",
  "/fablestage"
];

Deno.serve(() => {
  const lines = [
    '# GlyphLock LLC — canonical crawler policy',
    '# Public marketing and Technical Evidence routes are crawlable.',
    ...USER_AGENTS.map((agent) => `User-agent: ${agent}`),
    'Allow: /',
    ...PRIVATE_ROUTES.map((route) => `Disallow: ${route}`),
    `Sitemap: ${SITE_URL}/sitemap.xml`,
    '',
  ];
  return new Response(lines.join('\n'), {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
      'Access-Control-Allow-Origin': '*',
    },
  });
});
