/**
 * settlementCsv — builds an accountant-friendly CSV from the daily settlement
 * data shown on DailySettlementDashboard and triggers a browser download.
 *
 * The file is laid out in three sections separated by blank rows:
 *   1. Header (venue, business date, status, lock metadata)
 *   2. Totals (cash, card, total_sales, variance, GlyphBucks activity)
 *   3. Driver payouts (one row per driver with status, drops, payout)
 *
 * Frozen rules respected:
 *   - total_sales = cash + card ONLY
 *   - GlyphBucks shown in their own rows, never added to total_sales
 *   - Driver payouts shown as disbursements, never as negative revenue
 */

function escape(cell) {
  if (cell === null || cell === undefined) return "";
  const s = String(cell);
  // Quote anything containing comma, quote, or newline; double up internal quotes
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function row(...cells) {
  return cells.map(escape).join(",");
}

function money(n) {
  const v = Number(n) || 0;
  return v.toFixed(2);
}

export function buildSettlementCsv({
  venueId,
  venueName,
  businessDate,
  status,
  metrics,
  driverPayouts = [],
  existingSettlement = null,
  generatedBy = "",
}) {
  const lines = [];

  // ── Section 1: Header ──────────────────────────────────────────────
  lines.push(row("DAILY SETTLEMENT REPORT"));
  lines.push(row("Venue", venueName || venueId || ""));
  lines.push(row("Venue ID", venueId || ""));
  lines.push(row("Business Date", businessDate || ""));
  lines.push(row("Status", status || "OPEN"));
  if (existingSettlement?.locked_by) {
    lines.push(row("Locked By", existingSettlement.locked_by));
    lines.push(row("Locked At", existingSettlement.locked_at || ""));
  }
  lines.push(row("Generated At", new Date().toISOString()));
  lines.push(row("Generated By", generatedBy || ""));
  lines.push("");

  // ── Section 2: Totals ──────────────────────────────────────────────
  lines.push(row("LINE", "AMOUNT (USD)", "NOTES"));
  lines.push(row("Cash Sales", money(metrics.cash_sales), ""));
  lines.push(row("Card Sales", money(metrics.card_sales), ""));
  lines.push(row("TOTAL SALES", money(metrics.total_sales), "cash + card ONLY (frozen rule)"));
  lines.push(row("Variance (Over/Short)", money(metrics.variance), "Z-Report reconciliation"));
  lines.push(row("Batch Reference", metrics.batch_reference || "—", ""));
  lines.push("");

  // GlyphBucks — informational only
  const gb = metrics.glyphbucks_activity || {};
  lines.push(row("GLYPHBUCKS ACTIVITY", "", "Liability instrument — NOT in total sales"));
  lines.push(row("GB Issued (count)", gb.issued_count || 0, ""));
  lines.push(row("GB Issued (face value)", money(gb.issued_face_value), ""));
  lines.push(row("GB Redeemed (count)", gb.redeemed_count || 0, ""));
  lines.push(row("GB Redeemed (face value)", money(gb.redeemed_face_value), ""));
  lines.push("");

  // Driver payouts roll-up
  lines.push(row("DRIVER PAYOUTS", "", "Disbursements (drawer-out) — not negative revenue"));
  lines.push(row("Processed total", money(metrics.driver_payouts_total), `${metrics.processed_count} driver(s)`));
  lines.push(row("Outstanding (PENDING)", money(metrics.driver_payouts_outstanding), `${metrics.pending_count} driver(s)`));
  lines.push("");

  // ── Section 3: Driver payout detail ────────────────────────────────
  lines.push(row(
    "Driver Name", "Driver Number", "Status",
    "Total Drops", "VIP Count", "Pass Count",
    "Base Payout", "Incentive Bonus", "VIP Kickback",
    "Total Payout", "Paid At", "Paid By"
  ));
  for (const d of driverPayouts) {
    lines.push(row(
      d.driver_name || "",
      d.driver_number || "",
      d.payout_status || d.status || "PENDING",
      d.total_drops || 0,
      d.vip_count || 0,
      d.pass_count || 0,
      money(d.base_payout),
      money(d.incentive_bonus),
      money(d.vip_kickback),
      money(d.total_payout),
      d.paid_at || "",
      d.paid_by || ""
    ));
  }

  return lines.join("\r\n");
}

export function downloadSettlementCsv(opts) {
  const csv = buildSettlementCsv(opts);
  const safeVenue = (opts.venueId || "venue").replace(/[^a-z0-9_-]/gi, "_");
  const safeDate = (opts.businessDate || "date").replace(/[^0-9-]/g, "");
  const filename = `settlement_${safeVenue}_${safeDate}.csv`;

  // BOM so Excel opens UTF-8 cleanly
  const blob = new Blob(["\uFEFF", csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  return filename;
}