import React, { useState } from 'react';
import { Zap, Check, X, Loader2, Copy, DollarSign, Clock, Server, Shield, Search } from 'lucide-react';
import SEOHead from '@/components/SEOHead';
import { toast } from 'sonner';

export default function GlyphLockPlayground() {
  const [apiKey, setApiKey] = useState('gl_demo_key_' + Math.random().toString(36).substr(2, 9));
  const [input, setInput] = useState('Explain quantum computing in simple terms');
  const [primaryModel, setPrimaryModel] = useState('openai:gpt-4-turbo');
  const [fallbackModels, setFallbackModels] = useState(['anthropic:claude-sonnet-4.5', 'gemini:gemini-pro']);
  const [temperature, setTemperature] = useState(0.7);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [executionLog, setExecutionLog] = useState([]);

  const availableModels = {
    openai: [
      { id: 'gpt-4-turbo', name: 'GPT-4 Turbo', cost: '$0.01/$0.03' },
      { id: 'gpt-4', name: 'GPT-4', cost: '$0.03/$0.06' },
      { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo', cost: '$0.0005/$0.0015' }
    ],
    anthropic: [
      { id: 'claude-opus-4', name: 'Claude Opus 4', cost: '$0.015/$0.075' },
      { id: 'claude-sonnet-4.5', name: 'Claude Sonnet 4.5', cost: '$0.003/$0.015' },
      { id: 'claude-haiku-4.5', name: 'Claude Haiku 4.5', cost: '$0.00025/$0.00125' }
    ],
    gemini: [
      { id: 'gemini-pro', name: 'Gemini Pro', cost: '$0.0005/$0.0015' },
      { id: 'gemini-ultra', name: 'Gemini Ultra', cost: '$0.001/$0.003' }
    ]
  };

  const simulateChainRun = async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    setExecutionLog([]);

    const log = [];
    const models = [primaryModel, ...fallbackModels];

    for (let i = 0; i < models.length; i++) {
      const model = models[i];
      const [provider, modelName] = model.split(':');
      
      log.push({
        timestamp: new Date().toISOString(),
        model,
        status: 'attempting',
        message: `Attempting ${provider.toUpperCase()} (${modelName})...`
      });
      setExecutionLog([...log]);

      await new Promise(resolve => setTimeout(resolve, 800));

      if (i === 0 || (i === 1 && Math.random() > 0.3)) {
        const inputTokens = Math.floor(input.length / 4);
        const outputTokens = Math.floor(Math.random() * 200) + 100;
        const latency = Math.floor(Math.random() * 2000) + 500;
        const cost = (inputTokens * 0.00001 + outputTokens * 0.00003);

        log.push({
          timestamp: new Date().toISOString(),
          model,
          status: 'success',
          message: `✓ Success! Generated ${outputTokens} tokens in ${latency}ms`
        });
        setExecutionLog([...log]);

        setResult({
          output: generateMockResponse(input),
          modelUsed: model,
          latencyMs: latency,
          tokensUsed: {
            input: inputTokens,
            output: outputTokens,
            total: inputTokens + outputTokens
          },
          cost: parseFloat(cost.toFixed(6)),
          cached: false
        });

        setLoading(false);
        return;
      } else {
        log.push({
          timestamp: new Date().toISOString(),
          model,
          status: 'failed',
          message: `✗ Failed: Rate limit exceeded. Trying fallback...`
        });
        setExecutionLog([...log]);
      }
    }

    log.push({
      timestamp: new Date().toISOString(),
      model: 'system',
      status: 'failed',
      message: '✗ All models failed. Please try again.'
    });
    setExecutionLog([...log]);
    setError('All models failed to respond');
    setLoading(false);
  };

  const generateMockResponse = (prompt) => {
    const responses = {
      'quantum computing': 'Quantum computing is a revolutionary approach to computation that uses quantum mechanical phenomena like superposition and entanglement. Unlike classical computers that use bits (0 or 1), quantum computers use qubits which can exist in multiple states simultaneously. This allows them to solve certain complex problems exponentially faster than traditional computers, particularly in areas like cryptography, drug discovery, and optimization.',
      'explain': 'This is a detailed explanation generated by the AI model. The response demonstrates the multi-model orchestration system working correctly, with automatic fallback handling and cost optimization built in.',
      'default': 'This is a simulated AI response from the GlyphLock platform. In production, this would be a real response from OpenAI, Anthropic, or Google Gemini based on your configuration and availability.'
    };

    for (const [key, response] of Object.entries(responses)) {
      if (prompt.toLowerCase().includes(key)) {
        return response;
      }
    }
    return responses.default;
  };

  const toggleFallback = (model) => {
    if (fallbackModels.includes(model)) {
      setFallbackModels(fallbackModels.filter(m => m !== model));
    } else {
      setFallbackModels([...fallbackModels, model]);
    }
  };

  const copyCode = () => {
    navigator.clipboard.writeText(codeExample);
    toast.success('Code copied to clipboard');
  };

  const codeExample = `// Install the SDK
npm install glyphlock

// Import and initialize
const GlyphLock = require('glyphlock');

const gl = new GlyphLock({
  apiKey: "${apiKey}"
});

// Execute AI chain with automatic fallback
const result = await gl.chainRun({
  input: "${input}",
  model: "${primaryModel}",
  fallback: ${JSON.stringify(fallbackModels)},
  temperature: ${temperature}
});

// Use the results
console.log(result.output);
console.log("Model used:", result.modelUsed);
console.log("Cost: $" + result.cost);`;

  return (
    <>
      <SEOHead 
        title="GlyphLock AI Playground - Multi-Model Orchestration Demo"
        description="Interactive playground for GlyphLock's multi-AI orchestration platform with automatic failover between OpenAI, Anthropic, and Google Gemini."
      />
      
      <div className="min-h-screen bg-gradient-to-br from-slate-950 via-purple-950/30 to-slate-950 text-white p-4 md:p-8 pt-24">
        <div className="max-w-7xl mx-auto">
          <div className="mb-8">
            <div className="flex items-center gap-3 mb-2">
              <Zap className="w-8 h-8 text-cyan-400 drop-shadow-[0_0_8px_rgba(6,182,212,0.8)]" />
              <h1 className="text-3xl md:text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-300 to-purple-300">GlyphLock AI Playground</h1>
            </div>
            <p className="text-slate-400">
              Multi-model AI orchestration with automatic fallback • Built by Carlo René Earl
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="space-y-6">
              <div className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 border-2 border-purple-500/30">
                <label className="block text-sm font-medium mb-2 text-slate-300">API Key</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={apiKey}
                    onChange={(e) => setApiKey(e.target.value)}
                    className="flex-1 bg-slate-900/60 border border-purple-500/30 rounded-xl px-3 py-2 text-sm font-mono text-cyan-300 focus:outline-none focus:ring-2 focus:ring-cyan-500"
                    placeholder="gl_your_api_key"
                  />
                  <button
                    onClick={() => { navigator.clipboard.writeText(apiKey); toast.success('Copied'); }}
                    className="px-3 py-2 bg-cyan-500/20 border border-cyan-500/50 rounded-xl hover:bg-cyan-500/30 transition"
                  >
                    <Copy className="w-4 h-4 text-cyan-400" />
                  </button>
                </div>
              </div>

              <div className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 border-2 border-purple-500/30">
                <label className="block text-sm font-medium mb-2 text-slate-300">Prompt</label>
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  className="w-full bg-slate-900/60 border border-purple-500/30 rounded-xl px-3 py-2 h-32 resize-none text-slate-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  placeholder="Enter your prompt..."
                />
              </div>

              <div className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 border-2 border-purple-500/30">
                <label className="block text-sm font-medium mb-3 text-slate-300">Primary Model</label>
                <select
                  value={primaryModel}
                  onChange={(e) => setPrimaryModel(e.target.value)}
                  className="w-full bg-slate-900/60 border border-purple-500/30 rounded-xl px-3 py-2 text-slate-200 focus:outline-none focus:ring-2 focus:ring-cyan-500"
                >
                  {Object.entries(availableModels).map(([provider, models]) => (
                    <optgroup key={provider} label={provider.toUpperCase()}>
                      {models.map(model => (
                        <option key={model.id} value={`${provider}:${model.id}`}>
                          {model.name} ({model.cost})
                        </option>
                      ))}
                    </optgroup>
                  ))}
                </select>
              </div>

              <div className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 border-2 border-purple-500/30">
                <label className="block text-sm font-medium mb-3 text-slate-300">
                  Fallback Models (in order)
                </label>
                <div className="space-y-2">
                  {Object.entries(availableModels).map(([provider, models]) =>
                    models.map(model => {
                      const fullId = `${provider}:${model.id}`;
                      const isSelected = fallbackModels.includes(fullId);
                      const isPrimary = primaryModel === fullId;
                      
                      if (isPrimary) return null;

                      return (
                        <button
                          key={fullId}
                          onClick={() => toggleFallback(fullId)}
                          className={`w-full flex items-center justify-between px-4 py-2 rounded-xl border-2 transition ${
                            isSelected
                              ? 'bg-cyan-500/20 border-cyan-500'
                              : 'bg-slate-900/60 border-purple-500/30 hover:border-purple-500/50'
                          }`}
                        >
                          <span className="text-sm text-slate-200">{model.name}</span>
                          <div className="flex items-center gap-2">
                            <span className="text-xs text-slate-400">{model.cost}</span>
                            {isSelected && <Check className="w-4 h-4 text-cyan-400" />}
                          </div>
                        </button>
                      );
                    })
                  )}
                </div>
              </div>

              <div className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 border-2 border-purple-500/30">
                <label className="block text-sm font-medium mb-2 text-slate-300">
                  Temperature: {temperature}
                </label>
                <input
                  type="range"
                  min="0"
                  max="2"
                  step="0.1"
                  value={temperature}
                  onChange={(e) => setTemperature(parseFloat(e.target.value))}
                  className="w-full"
                />
                <div className="flex justify-between text-xs text-slate-400 mt-1">
                  <span>Deterministic</span>
                  <span>Creative</span>
                </div>
              </div>

              <button
                onClick={simulateChainRun}
                disabled={loading}
                className="w-full bg-gradient-to-r from-cyan-600 to-purple-600 hover:from-cyan-500 hover:to-purple-500 disabled:from-slate-700 disabled:to-slate-700 disabled:cursor-not-allowed py-4 rounded-2xl font-semibold text-lg transition flex items-center justify-center gap-2 shadow-[0_0_30px_rgba(6,182,212,0.5)]"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Processing...
                  </>
                ) : (
                  <>
                    <Zap className="w-5 h-5" />
                    Execute Chain
                  </>
                )}
              </button>
            </div>

            <div className="space-y-6">
              <div className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 border-2 border-purple-500/30">
                <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                  <Server className="w-5 h-5 text-cyan-400" />
                  Execution Log
                </h3>
                <div className="bg-slate-900/60 rounded-xl p-4 h-48 overflow-y-auto font-mono text-xs">
                  {executionLog.length === 0 ? (
                    <div className="text-slate-500">Click "Execute Chain" to start...</div>
                  ) : (
                    executionLog.map((log, i) => (
                      <div
                        key={i}
                        className={`mb-2 ${
                          log.status === 'success'
                            ? 'text-green-400'
                            : log.status === 'failed'
                            ? 'text-red-400'
                            : 'text-slate-400'
                        }`}
                      >
                        {log.message}
                      </div>
                    ))
                  )}
                </div>
              </div>

              {result && (
                <>
                  <div className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 border-2 border-purple-500/30">
                    <h3 className="text-lg font-semibold mb-4">Response</h3>
                    <div className="bg-slate-900/60 rounded-xl p-4 text-sm leading-relaxed text-slate-200">
                      {result.output}
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-4">
                    <div className="bg-white/5 backdrop-blur-xl rounded-xl p-4 border-2 border-purple-500/30">
                      <div className="flex items-center gap-2 text-slate-400 text-sm mb-1">
                        <Server className="w-4 h-4" />
                        Model
                      </div>
                      <div className="font-semibold text-cyan-300">{result.modelUsed.split(':')[1]}</div>
                    </div>
                    <div className="bg-white/5 backdrop-blur-xl rounded-xl p-4 border-2 border-purple-500/30">
                      <div className="flex items-center gap-2 text-slate-400 text-sm mb-1">
                        <Clock className="w-4 h-4" />
                        Latency
                      </div>
                      <div className="font-semibold text-purple-300">{result.latencyMs}ms</div>
                    </div>
                    <div className="bg-white/5 backdrop-blur-xl rounded-xl p-4 border-2 border-purple-500/30">
                      <div className="flex items-center gap-2 text-slate-400 text-sm mb-1">
                        <DollarSign className="w-4 h-4" />
                        Cost
                      </div>
                      <div className="font-semibold text-emerald-300">${result.cost.toFixed(6)}</div>
                    </div>
                  </div>

                  <div className="bg-white/5 backdrop-blur-xl rounded-xl p-4 border-2 border-purple-500/30">
                    <div className="text-sm text-slate-400 mb-2">Tokens Used</div>
                    <div className="flex items-center gap-4 text-sm text-slate-200">
                      <span>Input: <strong className="text-cyan-400">{result.tokensUsed.input}</strong></span>
                      <span>Output: <strong className="text-purple-400">{result.tokensUsed.output}</strong></span>
                      <span>Total: <strong className="text-white">{result.tokensUsed.total}</strong></span>
                    </div>
                  </div>
                </>
              )}

              {error && (
                <div className="bg-red-900/20 border-2 border-red-500 rounded-xl p-4 flex items-center gap-3">
                  <X className="w-5 h-5 text-red-400 flex-shrink-0" />
                  <span className="text-red-200">{error}</span>
                </div>
              )}

              <div className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 border-2 border-purple-500/30">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold">Code Example</h3>
                  <button
                    onClick={copyCode}
                    className="px-3 py-1 bg-cyan-500/20 border border-cyan-500/50 rounded-lg hover:bg-cyan-500/30 transition flex items-center gap-2 text-sm"
                  >
                    <Copy className="w-3 h-3" />
                    Copy
                  </button>
                </div>
                <pre className="bg-slate-900/60 rounded-xl p-4 text-xs overflow-x-auto">
                  <code className="text-cyan-300">{codeExample}</code>
                </pre>
              </div>
            </div>
          </div>

          <div className="mt-8 text-center text-slate-400 text-sm">
            <p>GlyphLock LLC • Built by Carlo René Earl • Arizona Entity ID: 23831258</p>
            <p className="mt-1">Multi-AI orchestration platform with automatic failover</p>
          </div>
        </div>
      </div>
    </>
  );
}