import { Sparkles, Bot, QrCode, Gauge, ShieldCheck, FileSignature, Workflow, Image, Music2, Building2, DollarSign, Radio, Search } from 'lucide-react';

export const layers = [
  { id:'CREATE', icon:Sparkles, color:'#d946ef', summary:'Create assets and experiences that can move into the rest of the GlyphLock system.' },
  { id:'INTELLIGENCE', icon:Bot, color:'#818cf8', summary:'Analyze, assist, inspect and orchestrate information before human-owned decisions.' },
  { id:'VERIFY', icon:QrCode, color:'#22d3ee', summary:'Give people, assets and records resolvable identifiers and inspectable verification events.' },
  { id:'OPERATE', icon:Gauge, color:'#38bdf8', summary:'Run real operational workflows and create the records that describe what happened.' },
  { id:'PROTECT', icon:ShieldCheck, color:'#f43f5e', summary:'Apply access boundaries, activity visibility and security-oriented operational controls.' },
  { id:'GOVERN', icon:FileSignature, color:'#f59e0b', summary:'Expose rules, evidence discipline, responsibilities, documentation and review methodology.' },
  { id:'CONNECT', icon:Workflow, color:'#10b981', summary:'Connect GlyphLock workflows to APIs, providers, infrastructure and external systems.' },
];

export const modules = [
  { name:'Image Lab', icon:Image, layer:'CREATE', status:'LIVE', route:'ImageLab', action:'OPEN IMAGE LAB', what:'Generate and analyze images and build interactive image experiences.', capabilities:['AI image generation','Visual analysis','Interactive hotspots'], connects:['GlyphBot','QR Studio'], evidence:'Working Image Lab and image-generation interfaces are available in the platform.' },
  { name:'DJ Pro Mixer', icon:Music2, layer:'CREATE', status:'LIVE', route:'GlyphBotMixer', action:'OPEN THE MIXER', what:'Creator and venue-facing audio/DJ workspace inside the GlyphLock ecosystem.', capabilities:['Interactive mixer UI','Creator workflow surface','Venue-facing tooling'], connects:['NUPS','GlyphBot'], evidence:'Interactive DJ/audio tooling is implemented as a usable product surface.' },
  { name:'GlyphBot', icon:Bot, layer:'INTELLIGENCE', status:'LIVE', route:'GlyphBot', action:'ASK GLYPHBOT', what:'Multi-provider AI workspace for research, analysis, code assistance, review and workflows.', capabilities:['Research assistance','Code analysis','Workflow support'], connects:['Site Audit','Image Lab','Governance Hub'], evidence:'Interactive GlyphBot assistant and supporting workflow components are implemented.' },
  { name:'Site Audit', icon:Search, layer:'INTELLIGENCE', status:'LIVE', route:'GlyphBot', action:'RUN A SITE AUDIT', what:'Inspect digital properties, organize findings and turn them into remediation work.', capabilities:['Site analysis','Finding organization','Remediation output'], connects:['GlyphBot','Security Operations','Governance Hub'], evidence:'Site-audit workflows are exposed through the GlyphBot product surface.' },
  { name:'QR Studio', icon:QrCode, layer:'VERIFY', status:'LIVE', route:'Qr', action:'CREATE A GLYPH', what:'Generate, encode, distribute, scan, resolve and verify QR/Glyph-linked records.', capabilities:['QR generation','Payload workflows','Scan logging','Signing options','Verification'], connects:['NUPS','Image Lab','Governance Hub'], evidence:'Generator, payload, scan, signing and verification workflows are implemented in-product.' },
  { name:'NUPS', icon:Building2, layer:'OPERATE', status:'FLAGSHIP · LIVE', route:'NUPSLanding', action:'ENTER NUPS', what:'GlyphLock’s flagship venue operating environment and strongest real-world system implementation.', capabilities:['Front door','POS/registers','Contracts','Staff/entertainer workflows','VIP','Payouts','Reporting','QR operations'], connects:['QR Studio','GlyphLock Financial','Security Operations','Governance Hub','Integrations'], evidence:'Working venue workflows, contracts, POS, reporting and integration surfaces are present in the product.' },
  { name:'GlyphLock Financial', icon:DollarSign, layer:'OPERATE', status:'LIVE', route:'GlyphLockFinancial', action:'VIEW FINANCIAL', what:'Operational financial surfaces for ledgers, settlements, payouts, reconciliation and reporting.', capabilities:['Ledgers','Settlement views','Payout workflows','Reconciliation','Reporting'], connects:['NUPS','Governance Hub'], evidence:'Ledger, settlement, payout, reconciliation and reporting interfaces are implemented.' },
  { name:'Security Operations', icon:Radio, layer:'PROTECT', status:'LIVE · HARDENING', route:'SecurityOperationsCenter', action:'INSPECT SECURITY', what:'Operational security visibility around access, activity, events and audit records.', capabilities:['Access visibility','Activity monitoring','Audit events','Security operations'], connects:['NUPS','Site Audit','Governance Hub'], evidence:'Security-operations surfaces are implemented; control hardening and independent validation remain separate work.' },
  { name:'Governance Hub', icon:FileSignature, layer:'GOVERN', status:'LIVE', route:'GovernanceHub', action:'EXPLORE GOVERNANCE', what:'The public control plane for GlyphLock governance concepts, review methodology and evidence discipline.', capabilities:['Master Covenant','Architecture review','Evidence boundaries','Remediation methodology'], connects:['All platform layers'], evidence:'Published framework, review methodology, documentation and public-claims boundaries are available.' },
  { name:'Integration Layer', icon:Workflow, layer:'CONNECT', status:'ACTIVE', route:'Services', action:'EXPLORE INTEGRATIONS', what:'APIs, OAuth, payments, hospitality integrations and infrastructure that connect GlyphLock outward.', capabilities:['APIs','OAuth','Payments','Oracle OHIP work','External services'], connects:['NUPS','GlyphBot','QR Studio','Financial'], evidence:'Multiple integration surfaces exist in the codebase; each external connection is validated according to its own scope.' },
];