/**
 * GlyphLock QR Studio - Complete Payload Type Catalog
 * Military-grade to consumer-friendly payload definitions
 */

import { 
  Link2, Globe, Clock, MapPin, Smartphone, User, Mail, Phone, 
  CreditCard, Bitcoin, Shield, FileText, Image, Music, Video,
  Wifi, Bluetooth, QrCode, Lock, Key, Database, Cloud, Zap,
  Package, Ticket, Gift, Heart, Briefcase, Building, Wrench,
  Camera, Sparkles, Layers, Binary, Code, Terminal
} from 'lucide-react';

export const PAYLOAD_CATEGORIES = {
  URL_REDIRECT: 'URL & Redirects',
  CONTACT: 'Contact & Identity',
  PAYMENT: 'Payment & Financial',
  AUTH: 'Authentication & Security',
  MEDICAL: 'Medical & Healthcare',
  RETAIL: 'Retail & Events',
  DATA: 'File & Data',
  MEDIA: 'Creative & Media',
  IOT: 'IoT & Infrastructure',
  MILITARY: 'Military & High Security',
  BLOCKCHAIN: 'Blockchain',
  GLYPHLOCK: 'GlyphLock Proprietary',
};

export const PAYLOAD_TYPES = [
  // URL & Redirects
  { 
    id: 'url', 
    label: 'URL Redirect', 
    icon: Link2, 
    category: PAYLOAD_CATEGORIES.URL_REDIRECT,
    description: 'Standard web URL redirect',
    placeholder: 'https://example.com',
    premium: false,
  },
  { 
    id: 'url_dynamic', 
    label: 'Dynamic URL', 
    icon: Globe, 
    category: PAYLOAD_CATEGORIES.URL_REDIRECT,
    description: 'Editable redirect URL after creation',
    placeholder: 'https://redirect.example.com',
    premium: false,
  },
  { 
    id: 'url_timelock', 
    label: 'Time-Locked URL', 
    icon: Clock, 
    category: PAYLOAD_CATEGORIES.URL_REDIRECT,
    description: 'URL only accessible during specific time windows',
    placeholder: 'https://example.com (Available: 9AM-5PM)',
    premium: false,
  },
  { 
    id: 'url_geolock', 
    label: 'Geo-Locked URL', 
    icon: MapPin, 
    category: PAYLOAD_CATEGORIES.URL_REDIRECT,
    description: 'URL only accessible from specific locations',
    placeholder: 'https://example.com (Radius: 100m)',
    premium: false,
  },
  { 
    id: 'url_velocity', 
    label: 'Velocity-Locked URL', 
    icon: Zap, 
    category: PAYLOAD_CATEGORIES.URL_REDIRECT,
    description: 'Requires specific scanning velocity/pattern',
    placeholder: 'https://example.com (Speed threshold: 5 scans/min)',
    premium: false,
  },
  { 
    id: 'url_device', 
    label: 'Device-Restricted URL', 
    icon: Smartphone, 
    category: PAYLOAD_CATEGORIES.URL_REDIRECT,
    description: 'Only accessible from specific device types',
    placeholder: 'https://example.com (iOS only)',
    premium: false,
  },

  // Contact & Identity
  { 
    id: 'vcard', 
    label: 'vCard', 
    icon: User, 
    category: PAYLOAD_CATEGORIES.CONTACT,
    description: 'Digital business card with contact info',
    placeholder: 'Name, Email, Phone, Address...',
    premium: false,
  },
  { 
    id: 'mecard', 
    label: 'MeCard', 
    icon: User, 
    category: PAYLOAD_CATEGORIES.CONTACT,
    description: 'Compact contact format (Japan standard)',
    placeholder: 'MECARD:N:Doe,John;TEL:1234567890;',
    premium: false,
  },
  { 
    id: 'linkedin', 
    label: 'LinkedIn Profile', 
    icon: Briefcase, 
    category: PAYLOAD_CATEGORIES.CONTACT,
    description: 'Direct link to LinkedIn profile',
    placeholder: 'https://linkedin.com/in/username',
    premium: false,
  },
  { 
    id: 'digital_card', 
    label: 'Digital Business Card', 
    icon: Building, 
    category: PAYLOAD_CATEGORIES.CONTACT,
    description: 'Enhanced vCard with branding',
    placeholder: 'Full contact + logo + company info',
    premium: false,
  },
  { 
    id: 'tap_call', 
    label: 'Tap-to-Call', 
    icon: Phone, 
    category: PAYLOAD_CATEGORIES.CONTACT,
    description: 'Instant phone dialer trigger',
    placeholder: 'tel:+1234567890',
    premium: false,
  },
  { 
    id: 'tap_text', 
    label: 'Tap-to-Text', 
    icon: Mail, 
    category: PAYLOAD_CATEGORIES.CONTACT,
    description: 'Pre-filled SMS message',
    placeholder: 'sms:+1234567890?body=Hello',
    premium: false,
  },
  { 
    id: 'email_template', 
    label: 'Email Template', 
    icon: Mail, 
    category: PAYLOAD_CATEGORIES.CONTACT,
    description: 'Pre-filled email with subject and body',
    placeholder: 'mailto:contact@example.com?subject=Inquiry',
    premium: false,
  },

  // Payment & Financial
  { 
    id: 'payment_upi', 
    label: 'UPI Payment (India)', 
    icon: CreditCard, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'Unified Payments Interface',
    placeholder: 'upi://pay?pa=merchant@upi&pn=Name&am=100',
    premium: false,
  },
  { 
    id: 'payment_paypal', 
    label: 'PayPal', 
    icon: CreditCard, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'PayPal.me payment link',
    placeholder: 'https://paypal.me/username/50',
    premium: false,
  },
  { 
    id: 'payment_cashapp', 
    label: 'CashApp', 
    icon: CreditCard, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'Cash App payment request',
    placeholder: 'https://cash.app/$username',
    premium: false,
  },
  { 
    id: 'payment_venmo', 
    label: 'Venmo', 
    icon: CreditCard, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'Venmo payment request',
    placeholder: 'venmo://paycharge?txn=pay&recipients=username',
    premium: false,
  },
  { 
    id: 'payment_stripe', 
    label: 'Stripe Payment Link', 
    icon: CreditCard, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'Direct Stripe checkout link',
    placeholder: 'https://buy.stripe.com/...',
    premium: false,
  },
  { 
    id: 'crypto_btc', 
    label: 'Bitcoin Wallet', 
    icon: Bitcoin, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'BTC wallet address',
    placeholder: 'bitcoin:1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
    premium: false,
  },
  { 
    id: 'crypto_eth', 
    label: 'Ethereum Wallet', 
    icon: Bitcoin, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'ETH wallet address',
    placeholder: 'ethereum:0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
    premium: false,
  },
  { 
    id: 'crypto_sol', 
    label: 'Solana Wallet', 
    icon: Bitcoin, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'SOL wallet address',
    placeholder: 'solana:7v91N7iZ9mNicL8WfG6cgSCKyRXydQjLh6UYBWwm6y1Q',
    premium: false,
  },
  { 
    id: 'payment_nups', 
    label: 'NUPS Driver Payout', 
    icon: Package, 
    category: PAYLOAD_CATEGORIES.PAYMENT,
    description: 'GlyphLock NUPS driver compensation QR',
    placeholder: 'nups://payout?driver_id=xxx',
    premium: false,
  },

  // Authentication & Security
  { 
    id: 'auth_oauth', 
    label: 'OAuth Login', 
    icon: Key, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'Trigger OAuth authentication flow',
    placeholder: 'oauth://authorize?client_id=xxx',
    premium: false,
  },
  { 
    id: 'auth_sso', 
    label: 'SSO Deep Link', 
    icon: Shield, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'Enterprise single sign-on trigger',
    placeholder: 'sso://login?provider=okta',
    premium: false,
  },
  { 
    id: 'auth_2fa', 
    label: '2FA/MFA Booster', 
    icon: Lock, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'Multi-factor authentication code',
    placeholder: 'totp://username?secret=xxx',
    premium: false,
  },
  { 
    id: 'auth_session', 
    label: 'Session Token', 
    icon: Terminal, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'Initiate authenticated session',
    placeholder: 'session://start?token=xxx',
    premium: false,
  },
  { 
    id: 'auth_temp_access', 
    label: 'Temporary Access Code', 
    icon: Clock, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'Time-limited access token',
    placeholder: 'access://temp?code=xxx&expires=3600',
    premium: false,
  },
  { 
    id: 'auth_encrypted', 
    label: 'Encrypted Session', 
    icon: Lock, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'E2EE session initialization',
    placeholder: 'encrypted://session?key=xxx',
    premium: false,
  },
  { 
    id: 'auth_badge', 
    label: 'Employee Badge', 
    icon: User, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'Enterprise employee verification',
    placeholder: 'badge://employee?id=xxx',
    premium: false,
  },
  { 
    id: 'auth_visitor', 
    label: 'Visitor Pass', 
    icon: Building, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'Temporary building access',
    placeholder: 'visitor://pass?id=xxx&valid_until=xxx',
    premium: false,
  },
  { 
    id: 'auth_nfc', 
    label: 'NFC+QR Dual Token', 
    icon: Zap, 
    category: PAYLOAD_CATEGORIES.AUTH,
    description: 'Combined NFC and QR authentication',
    placeholder: 'dual://auth?qr_id=xxx&nfc_id=xxx',
    premium: false,
  },

  // Medical & Healthcare
  { 
    id: 'medical_record', 
    label: 'Patient Record Lookup', 
    icon: FileText, 
    category: PAYLOAD_CATEGORIES.MEDICAL,
    description: 'HIPAA-aligned patient data access controls',
    placeholder: 'medical://record?patient_id=xxx',
    premium: false,
  },
  { 
    id: 'medical_prescription', 
    label: 'Prescription Verification', 
    icon: Heart, 
    category: PAYLOAD_CATEGORIES.MEDICAL,
    description: 'Verify prescription authenticity',
    placeholder: 'rx://verify?prescription_id=xxx',
    premium: false,
  },
  { 
    id: 'medical_allergy', 
    label: 'Allergy & Emergency Info', 
    icon: Heart, 
    category: PAYLOAD_CATEGORIES.MEDICAL,
    description: 'Critical medical information',
    placeholder: 'emergency://info?patient_id=xxx',
    premium: false,
  },
  { 
    id: 'medical_id', 
    label: 'Medical ID Bracelet', 
    icon: Heart, 
    category: PAYLOAD_CATEGORIES.MEDICAL,
    description: 'Wearable medical ID QR',
    placeholder: 'medid://patient?id=xxx',
    premium: false,
  },
  { 
    id: 'medical_insurance', 
    label: 'Insurance Verification', 
    icon: Shield, 
    category: PAYLOAD_CATEGORIES.MEDICAL,
    description: 'Insurance card QR',
    placeholder: 'insurance://verify?policy=xxx',
    premium: false,
  },

  // Retail & Events
  { 
    id: 'retail_coupon', 
    label: 'Coupon', 
    icon: Gift, 
    category: PAYLOAD_CATEGORIES.RETAIL,
    description: 'Discount coupon code',
    placeholder: 'coupon://redeem?code=SAVE20',
    premium: false,
  },
  { 
    id: 'retail_loyalty', 
    label: 'Loyalty Points', 
    icon: Heart, 
    category: PAYLOAD_CATEGORIES.RETAIL,
    description: 'Loyalty program QR',
    placeholder: 'loyalty://account?member_id=xxx',
    premium: false,
  },
  { 
    id: 'event_ticket', 
    label: 'Event Ticket', 
    icon: Ticket, 
    category: PAYLOAD_CATEGORIES.RETAIL,
    description: 'Digital event ticket',
    placeholder: 'ticket://event?id=xxx',
    premium: false,
  },
  { 
    id: 'event_entry', 
    label: 'Verified Entry Pass', 
    icon: Shield, 
    category: PAYLOAD_CATEGORIES.RETAIL,
    description: 'Secure event entry verification',
    placeholder: 'entry://verify?pass_id=xxx',
    premium: false,
  },
  { 
    id: 'retail_membership', 
    label: 'Membership Card', 
    icon: User, 
    category: PAYLOAD_CATEGORIES.RETAIL,
    description: 'Digital membership credentials',
    placeholder: 'member://card?id=xxx',
    premium: false,
  },
  { 
    id: 'retail_giftcard', 
    label: 'Gift Card Balance', 
    icon: Gift, 
    category: PAYLOAD_CATEGORIES.RETAIL,
    description: 'Check gift card balance',
    placeholder: 'giftcard://balance?card_id=xxx',
    premium: false,
  },
  { 
    id: 'retail_inventory', 
    label: 'Inventory Lookup', 
    icon: Package, 
    category: PAYLOAD_CATEGORIES.RETAIL,
    description: 'Product inventory check',
    placeholder: 'inventory://lookup?sku=xxx',
    premium: false,
  },

  // File & Data
  { 
    id: 'data_base64', 
    label: 'Base64 Data Embed', 
    icon: Code, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'Embedded base64 encoded data',
    placeholder: 'data:text/plain;base64,SGVsbG8gV29ybGQ=',
    premium: false,
  },
  { 
    id: 'data_json', 
    label: 'JSON Payload', 
    icon: Database, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'Structured JSON data',
    placeholder: '{"key": "value", "data": [...]}',
    premium: false,
  },
  { 
    id: 'data_yaml', 
    label: 'YAML Payload', 
    icon: FileText, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'YAML configuration data',
    placeholder: 'key: value\ndata:\n  - item1',
    premium: false,
  },
  { 
    id: 'data_csv', 
    label: 'CSV Download Trigger', 
    icon: FileText, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'Download CSV file',
    placeholder: 'https://example.com/data.csv',
    premium: false,
  },
  { 
    id: 'file_gdrive', 
    label: 'Google Drive File', 
    icon: Cloud, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'Open Google Drive file',
    placeholder: 'https://drive.google.com/file/d/xxx',
    premium: false,
  },
  { 
    id: 'file_dropbox', 
    label: 'Dropbox File', 
    icon: Cloud, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'Open Dropbox file',
    placeholder: 'https://dropbox.com/s/xxx',
    premium: false,
  },
  { 
    id: 'wifi_config', 
    label: 'WiFi Configuration', 
    icon: Wifi, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'WiFi SSID and password',
    placeholder: 'WIFI:T:WPA;S:NetworkName;P:Password;;',
    premium: false,
  },
  { 
    id: 'bluetooth_pair', 
    label: 'Bluetooth Pairing', 
    icon: Bluetooth, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'Bluetooth device pairing info',
    placeholder: 'bt://pair?device=xxx',
    premium: false,
  },
  { 
    id: 'app_install', 
    label: 'App Install Deep Link', 
    icon: Smartphone, 
    category: PAYLOAD_CATEGORIES.DATA,
    description: 'iOS/Android app store link',
    placeholder: 'https://apps.apple.com/app/xxx',
    premium: false,
  },

  // Creative & Media
  { 
    id: 'media_gallery', 
    label: 'Image Gallery', 
    icon: Image, 
    category: PAYLOAD_CATEGORIES.MEDIA,
    description: 'Open photo gallery',
    placeholder: 'https://example.com/gallery',
    premium: false,
  },
  { 
    id: 'media_music', 
    label: 'Music Track/Playlist', 
    icon: Music, 
    category: PAYLOAD_CATEGORIES.MEDIA,
    description: 'Spotify, Apple Music, etc.',
    placeholder: 'https://open.spotify.com/track/xxx',
    premium: false,
  },
  { 
    id: 'media_hidden', 
    label: 'Hidden Message (Stego)', 
    icon: Layers, 
    category: PAYLOAD_CATEGORIES.MEDIA,
    description: 'Steganographic hidden layer',
    placeholder: 'stego://reveal?key=xxx',
    premium: false,
  },
  { 
    id: 'media_interactive', 
    label: 'Interactive Art Trigger', 
    icon: Sparkles, 
    category: PAYLOAD_CATEGORIES.MEDIA,
    description: 'Trigger interactive art experience',
    placeholder: 'art://interact?piece_id=xxx',
    premium: false,
  },
  { 
    id: 'media_merch', 
    label: 'Scannable Merchandise', 
    icon: Package, 
    category: PAYLOAD_CATEGORIES.MEDIA,
    description: 'Product authentication QR',
    placeholder: 'merch://verify?product_id=xxx',
    premium: false,
  },
  { 
    id: 'media_ar', 
    label: 'AR Object Loader', 
    icon: Camera, 
    category: PAYLOAD_CATEGORIES.MEDIA,
    description: 'Load augmented reality content',
    placeholder: 'ar://load?model=xxx',
    premium: false,
  },
  { 
    id: 'media_video', 
    label: 'Video Autostart', 
    icon: Video, 
    category: PAYLOAD_CATEGORIES.MEDIA,
    description: 'YouTube, Vimeo, custom video',
    placeholder: 'https://youtube.com/watch?v=xxx',
    premium: false,
  },

  // IoT & Infrastructure
  { 
    id: 'iot_device', 
    label: 'IoT Device Config', 
    icon: Wrench, 
    category: PAYLOAD_CATEGORIES.IOT,
    description: 'Configure IoT device',
    placeholder: 'iot://config?device_id=xxx',
    premium: false,
  },
  { 
    id: 'iot_smarthome', 
    label: 'Smart Home Pairing', 
    icon: Building, 
    category: PAYLOAD_CATEGORIES.IOT,
    description: 'Pair smart home device',
    placeholder: 'smarthome://pair?device=xxx',
    premium: false,
  },
  { 
    id: 'iot_industrial', 
    label: 'Industrial Equipment Log', 
    icon: Wrench, 
    category: PAYLOAD_CATEGORIES.IOT,
    description: 'Equipment service log access',
    placeholder: 'industrial://log?equipment_id=xxx',
    premium: false,
  },
  { 
    id: 'iot_router', 
    label: 'Router Setup', 
    icon: Wifi, 
    category: PAYLOAD_CATEGORIES.IOT,
    description: 'Router configuration QR',
    placeholder: 'router://setup?ssid=xxx',
    premium: false,
  },
  { 
    id: 'iot_diagnostics', 
    label: 'Machine Diagnostics', 
    icon: Terminal, 
    category: PAYLOAD_CATEGORIES.IOT,
    description: 'Equipment diagnostic data',
    placeholder: 'diagnostics://machine?id=xxx',
    premium: false,
  },
  { 
    id: 'iot_factory', 
    label: 'Factory Floor Access', 
    icon: Building, 
    category: PAYLOAD_CATEGORIES.IOT,
    description: 'Factory floor authorization',
    placeholder: 'factory://access?zone=xxx',
    premium: false,
  },

  // Military & High Security
  { 
    id: 'military_dual_encrypted', 
    label: 'Dual-Layer Encrypted', 
    icon: Shield, 
    category: PAYLOAD_CATEGORIES.MILITARY,
    description: 'Military-grade dual encryption',
    placeholder: 'encrypted://dual?key1=xxx&key2=xxx',
    premium: false,
  },
  { 
    id: 'military_camo', 
    label: 'Camouflage-Embedded QR', 
    icon: Layers, 
    category: PAYLOAD_CATEGORIES.MILITARY,
    description: 'Visually disguised QR code',
    placeholder: 'camo://embed?image=xxx',
    premium: false,
  },
  { 
    id: 'military_motion', 
    label: 'Motion-Verified Command', 
    icon: Zap, 
    category: PAYLOAD_CATEGORIES.MILITARY,
    description: 'Requires specific motion pattern to unlock',
    placeholder: 'motion://verify?pattern=xxx',
    premium: false,
  },
  { 
    id: 'military_geoproof', 
    label: 'Proof-of-Location Token', 
    icon: MapPin, 
    category: PAYLOAD_CATEGORIES.MILITARY,
    description: 'Cryptographic location verification',
    placeholder: 'geoproof://verify?coords=xxx',
    premium: false,
  },
  { 
    id: 'military_offline', 
    label: 'Offline Command Validation', 
    icon: Terminal, 
    category: PAYLOAD_CATEGORIES.MILITARY,
    description: 'Air-gapped command verification',
    placeholder: 'offline://command?hash=xxx',
    premium: false,
  },
  { 
    id: 'military_onetime', 
    label: 'One-Time Mission Packet', 
    icon: Lock, 
    category: PAYLOAD_CATEGORIES.MILITARY,
    description: 'Self-destructing single-use QR',
    placeholder: 'onetime://mission?token=xxx',
    premium: false,
  },
  { 
    id: 'military_tamper', 
    label: 'Tamper-Reactive Payload', 
    icon: Shield, 
    category: PAYLOAD_CATEGORIES.MILITARY,
    description: 'Detects and reacts to tampering',
    placeholder: 'tamper://reactive?signature=xxx',
    premium: false,
  },
  { 
    id: 'military_stego', 
    label: 'Steganographic 2nd Layer', 
    icon: Layers, 
    category: PAYLOAD_CATEGORIES.MILITARY,
    description: 'Hidden data in QR image',
    placeholder: 'stego://layer2?key=xxx',
    premium: false,
  },

  // Blockchain
  { 
    id: 'blockchain_wallet', 
    label: 'Wallet Verification', 
    icon: Bitcoin, 
    category: PAYLOAD_CATEGORIES.BLOCKCHAIN,
    description: 'Verify blockchain wallet ownership',
    placeholder: 'blockchain://verify?wallet=xxx',
    premium: false,
  },
  { 
    id: 'blockchain_nft', 
    label: 'NFT Ownership Claim', 
    icon: Image, 
    category: PAYLOAD_CATEGORIES.BLOCKCHAIN,
    description: 'Prove NFT ownership',
    placeholder: 'nft://claim?token_id=xxx',
    premium: false,
  },
  { 
    id: 'blockchain_contract', 
    label: 'Smart Contract Trigger', 
    icon: Code, 
    category: PAYLOAD_CATEGORIES.BLOCKCHAIN,
    description: 'Execute smart contract function',
    placeholder: 'contract://execute?address=xxx&function=xxx',
    premium: false,
  },
  { 
    id: 'blockchain_timestamp', 
    label: 'Timestamp Proof (OTS)', 
    icon: Clock, 
    category: PAYLOAD_CATEGORIES.BLOCKCHAIN,
    description: 'OpenTimestamps verification',
    placeholder: 'ots://verify?hash=xxx',
    premium: false,
  },
  { 
    id: 'blockchain_id', 
    label: 'Blockchain ID Binding', 
    icon: User, 
    category: PAYLOAD_CATEGORIES.BLOCKCHAIN,
    description: 'Bind identity to blockchain',
    placeholder: 'id://bind?chain=xxx&address=xxx',
    premium: false,
  },
  { 
    id: 'blockchain_handshake', 
    label: 'Off-Chain to On-Chain', 
    icon: Link2, 
    category: PAYLOAD_CATEGORIES.BLOCKCHAIN,
    description: 'Bridge off-chain and on-chain data',
    placeholder: 'bridge://handshake?proof=xxx',
    premium: false,
  },

  // GlyphLock Proprietary
  { 
    id: 'glx_truststrike', 
    label: 'GLX TrustStrike Payload', 
    icon: Zap, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'GlyphLock trust verification system',
    placeholder: 'glx://truststrike?signature=xxx',
    premium: false,
  },
  { 
    id: 'glx_covenant', 
    label: 'Master Covenant Auto-Bind', 
    icon: Shield, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Automatic covenant binding',
    placeholder: 'covenant://bind?master_id=xxx',
    premium: false,
  },
  { 
    id: 'glx_cab', 
    label: 'CAB Signature Packet', 
    icon: FileText, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Cryptographic Authorization Bundle',
    placeholder: 'cab://signature?bundle=xxx',
    premium: false,
  },
  { 
    id: 'glx_bpaaa', 
    label: 'BPAAA-Verified Identity', 
    icon: User, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Biometric-Predictive AI Authentication',
    placeholder: 'bpaaa://verify?identity=xxx',
    premium: false,
  },
  { 
    id: 'glx_touch', 
    label: 'GlyphTouch Trigger', 
    icon: Sparkles, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Proprietary touch interaction system',
    placeholder: 'glyphtouch://trigger?action=xxx',
    premium: false,
  },
  { 
    id: 'glx_emotion', 
    label: 'Emotion-Reactive Scan', 
    icon: Heart, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Bio-signal reactive payload',
    placeholder: 'emotion://react?biometric=xxx',
    premium: false,
  },
  { 
    id: 'glx_dac', 
    label: 'DACΩ Authority Command', 
    icon: Terminal, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Distributed Authority Command',
    placeholder: 'dac://command?authority=xxx',
    premium: false,
  },
  { 
    id: 'glx_voucher', 
    label: 'NUPS Club Voucher', 
    icon: Ticket, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Dream Palace, Skin/Bones Cabaret voucher',
    placeholder: 'voucher://nups?club=xxx&amount=xxx',
    premium: false,
  },
  { 
    id: 'glx_hotzone', 
    label: 'Interactive Image Hot-Zone', 
    icon: Layers, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Multi-zone interactive image',
    placeholder: 'hotzone://image?zones=xxx',
    premium: false,
  },
  { 
    id: 'glx_driver_payout', 
    label: 'Driver Payout Route', 
    icon: Package, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'NUPS driver compensation routing',
    placeholder: 'payout://driver?route=xxx',
    premium: false,
  },
  { 
    id: 'glx_story', 
    label: 'Interactive Story Fragment', 
    icon: Binary, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'Narrative fragment QR system',
    placeholder: 'story://fragment?chapter=xxx',
    premium: false,
  },
  { 
    id: 'glx_intelligence', 
    label: 'GlyphBot Intelligence Inheritance', 
    icon: QrCode, 
    category: PAYLOAD_CATEGORIES.GLYPHLOCK,
    description: 'AI knowledge transfer QR',
    placeholder: 'glyphbot://inherit?kb=xxx',
    premium: false,
  },
];

// Group by category helper
export const getPayloadsByCategory = () => {
  const grouped = {};
  Object.values(PAYLOAD_CATEGORIES).forEach(category => {
    grouped[category] = PAYLOAD_TYPES.filter(type => type.category === category);
  });
  return grouped;
};

// Search helper
export const searchPayloadTypes = (query) => {
  const lowerQuery = query.toLowerCase();
  return PAYLOAD_TYPES.filter(type => 
    type.label.toLowerCase().includes(lowerQuery) ||
    type.description.toLowerCase().includes(lowerQuery) ||
    type.category.toLowerCase().includes(lowerQuery)
  );
};